---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 1.2.1
  values:
    alloy:
      env:
        - name: HOST_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      configMap:
        create: true
        content: |-
          logging {
            level  = "info"
            format = "logfmt"
          }

          loki.write "default" {
            external_labels = {
              cluster = "production",
            }
            endpoint {
              url = "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
            }
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              action        = "keep"
              regex         = env("HOST_NODE_NAME")
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name", "__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
              regex         = "(.+);(.+);(.+)"
              target_label  = "__path__"
              replacement   = "/var/log/containers/${1}_${2}_${3}-*.log"
            }

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "replace"
              target_label = "namespace"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              action = "replace"
              target_label = "pod"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              action = "replace"
              target_label = "container"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              action = "replace"
              target_label = "app"
            }

            rule {
              source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
              action = "replace"
              target_label = "job"
              separator = "/"
              replacement = "$1"
            }

            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
              action        = "replace"
            }
          }

          loki.source.kubernetes "pod_logs" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.write.default.receiver]
          }
                    
          loki.source.kubernetes_events "default" {
            log_format = "logfmt"
            forward_to = [loki.write.default.receiver]
          }

      mounts:
        varlog: true
        dockercontainers: false

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
