apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: driver.longhorn.io
    volumeHandle: radarr-config
  claimRef:
    namespace: media
    name: radarr-config
