---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBVsbHeDC/pT3jlB7+PZ9EwjOzgYT6SzCuKbFxZeQpwsE3UKBIgflfXt6ECG74xOYBnOZbaRlRtKDfF21UWckLKTVZYC/ReI7de+pnPeHbjDEkZGrMb819OBEGCuvTu0ul/aQWC6kQ/+5dCb4UuWqRT0IRQ1z3b1uHIhaeuEAElPlW96bhord0tTnZgduaR5mFo7HZo6a1OkxGbqxJmt0UIE//fy6CgxmMhUOAttVDf1x7f/9iMIAY44B3goTblzbelKHm/uGLWRua7ZnIMsBYfKH6XnAI0JeAb7mhtSb3VM3cvTUV8TfL1t9IwRr+E4fJroScLDgtTI06TGt1Kkbw1qAZukezHivgs5N6uSWyT8c5eqCqz5efHb9jqNqAAW41Z+4GqSaJC3ZTQaGo8SahucfdBZub2AtaVAjys33cqRdd3ApecBiE9DaUJAtTF60x39yRcuDlRADKh+BVR2/jraBWr2VJt+5PApPE8GB7dzsKM9G90DM3yRyns9J0/kNOSKY1YkPlTijfmpZd/92Mh3ZHxUfKm98OuPFp94r+Ovi7JY0Kw8MFXMk3S0ze9dTvm1bapp8qFWTIGv6pgXkCP/4fH+fMZGqNC6J8Wc2TKmtGQCzEz5aSf73caaZnru8rZjIeIfyRuP0wFORuZxzsWoybvFz0ImutdCZoDR38v9oObvHsqZYziLe/a4oNUXl/cAHO/siQ8MjjuU4LH9/FW9mXAto7V5Sor0Hc7eOSNtLB3PtKfoyg+
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-secrets
      namespace: cert-manager
