---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: cert-manager-secrets
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: cert-manager_CLOUDFLARE_TOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-substitution
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: cert-manager-substitution
  data:
    - secretKey: EMAIL
      remoteRef:
        key: cert-manager_EMAIL
