apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultwarden.yaml
  - immich.yaml
  - media.yaml
  - home-assistant.yaml
  - outline.yaml
  - romm.yaml
  # - whatsmyip.yaml
