---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: romm
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 2m
  timeout: 8m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/romm
  prune: true
  wait: true
  dependsOn:
    - name: cluster-secrets
    - name: infrastructure-traefik
    - name: infrastructure-longhorn
    - name: infrastructure-cloudnative-pg-operator
  postBuild:
    substituteFrom:
      - kind: Secret
        name: ingress-secrets-system
        optional: false
