---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/vaultwarden
  prune: true
  wait: true
  dependsOn:
    - name: cluster-secrets
    - name: traefik
  postBuild:
    substituteFrom:
      - kind: Secret
        name: vaultwarden-secrets-system
        optional: false
      - kind: Secret
        name: ingress-secrets-system
        optional: false
