---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: authentik_AUTHENTIK_EMAIL__PASSWORD
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik_AUTHENTIK_SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: authentik_POSTGRES_PASSWORD
