apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whatsmyip-ingress
  namespace: whatsmyip
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`whatsmyip.${DOMAIN}`)"
      priority: 10
      services:
        - name: whatsmyip
          port: 80 
