apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-ingress
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`vw.${TLD}`)"
      priority: 10
      services:
        - name: vaultwarden
          port: 80
