---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/intel-gpu-plugin
  prune: false
  wait: true
  dependsOn:
    - name: nfd
    - name: cert-manager

