apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - cluster-secrets.yaml
  - notification.yaml
  - cert-manager.yaml
  - traefik.yaml
  - longhorn.yaml
  - cloudflare-ddns.yaml
  - docker-mailserver.yaml
  - authentik.yaml
  - cloudnative-pg.yaml
  - nfd.yaml
  - intel-gpu-plugin.yaml
  - monitoring.yaml
  - prometheus.yaml
