apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: recyclarr
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.0.1
  values:
    controllers:
      recyclarr:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.3@sha256:9c6c74d52cfc6f740a5a3624aa83867e171bb70b90453ddb7a4048b8c80445f9
            env:
              TZ: "America/Argentina/Buenos_Aires"
              CRON_SCHEDULE: "@daily"
    service:
      app:
        enabled: false
    persistence:
      config:
        existingClaim: recyclarr-config
        globalMounts:
          - path: /config
