apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: recyclarr
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.0.1
  values:
    controllers:
      recyclarr:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728
            env:
              TZ: "America/Argentina/Buenos_Aires"
              CRON_SCHEDULE: "@daily"
    service:
      app:
        enabled: false
    persistence:
      config:
        existingClaim: recyclarr-config
        globalMounts:
          - path: /config
