---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAtcK2JTaPrpqRB69mxmUbi4uDOpdMfroFNcx3JZs6u4fWLMeJt0AwXOQVXRKULOh329m1RU/pjc4/xkay0K0zraUqjxMNRzAHQHYNaO3V9hwx8mslgvY6a2GytInBi/kD/tyyPNXdwFhim74u7k4uiCnvABjy9vVH7bNkhGRTyytiBesnt0Y6ak6C+YQm780L53gvYIifqT1kTU99k+obD7o7TMeZRLaydGb27OKa3Zcoufi7hxR4eKEYJ3CNvXiLepjXQtIP/wwe6P5x7dvD5Kpmzlhcv6lQVqmLRa7DVn2FrOftj8m3Y6q+6OibZZL+VrCiexnJg4hhhgvYpETICXSNAUiyPxhDeUZBleVuINxqU28ZQruuoyys8ISsL6l6CU24PwYYxAm1Af4V2RyjJdqY+0J5Hqd2H26M7+Wj/Xkx5mMD57xusKGYBjyaGzm62/UCmOZC3G+rO4qZenaGHCZmgF/b3LKa8mRjOWGHc+cC3Y/uMWLnAxGndBMd1ehxopc0jHuURiya0o6XLmqTI0NLO+rKZKE53hHJlDxQrCUiV+9I/scBaaYokUsXq4GOUrJurmStp5t5xvQFT9UBApROCO4skH1tFPLw4XTS/l3dLniIrG5W/ZNc+XvnEZYrHwWvvfdVQciEkARRxMSWORjxLo5q3GPd3jYKsjzyNSxvPQsPXtlN0k4cKZFnQS6mdELKcvJVY6jgphtPUoGwuSGQ1Rq4b/4H1jFcvehd+3w==
    admin-user: AgATCGQYZRo7krM5neFfb72e6xjIL2L5s2maayDfXG/zBov8RHzrNhHc0bnHHvX8/ll7oQfuEg2MRKSnx9Ea0FUEqtgrqF+x+Vpv42VM7os80AWzgnmtbtRu6iAhLOc5x30beSMQsm/a+9cS7ixXMNDY7eGjg9+1ltNASj25LnMg8/2tzik+amumuHq+wGk452UQjrK1vPdLhsVG+NW/Mvehsrjn83M4jCMb/86a6bU3hRwoKtCGywc/PnrJC45nlPLvE05BhV1P+GoxiVYamjdLc1hM4ukj8gQEO18AS1HOS2j1i8oEJN5ZHOaNp74WPelJLUjDtxzHwI6maRcgU4OSZzQWK1cOhP1lpBfQxtr1Tr2YJVHT2Q+oGqfgG1QER23Cm5h/Z+2TBootur98LOHk17H4zNmqH9xyoURgF4UfqI3OEINDxo+VXcb4XxhOmROjIcqGJIuVJOeW5L/SD43zPgHFEoyf7qVQ+GToAYputUefEDW6QcdktcdCIbfIKyaImkSX56b1u0zjqDBjW65uIr6lo+8uZueWIVfZe4iHxYPOHNgCwBm/Ryip0IzPE6riUvBxlVtS0njGj3WhU3Nk/aHchdvI6WG9k+wXWvb8xR8sUFT15DgZi5xzoQVoV/9h+YR/EAozaNN6sLKslofdPN111Ki+oiKhnQ8O91Y/FDCaAPW4aj6latiNVrcakZ3YAk4YOg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: grafana
    type: Opaque
