---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA5ME64F/6YXxgonrvvT6bxNeLOw74Do9aIkuNZpAXIGFjy86FcJee5F///+j60cAO1D7N3h7vxUZ8XnC2V0saaaxDvUHdIAeVTCbrbbbC9GFFsoYwLcTjZLQcGwSvLu/BgnbH7y5Y2htUL+ZzKFCSpr2dxWoT3Uj4uwD/IR/aM69RJjSbis77zRGxEfjq7r0tcUUE+PcNRJcjrhDu3/mK5OeiRKdCRG3i0RVF/3y9Jv6krQO9mw3oOT95Gabh0/L8G+J5RoO95uRN3iXTfwXrDaWGfpAq8rFzvG55dM9jxgGPZUdjJd0Y6t3NQhtCRG3HcM9gU4IMeqPlH++8IN//YveHFHJHmzSgNViVdkRJvZXLbsoFqQJJT3k0B9kiIqNmCrQ2aqrwr4MiIWTyT+xgALMFczrkMgQGhSPKV99E0BOumt5uqFW2U3sxGm2jwQcT/DYMZkxiH3cVP1QWl0ChWhIV60BPnq3A7oSmXBp1DJ2l6Z+emjK3sIcJe9Yeqk+mglssJWCzOC209fqCzymE2WUD6EqtpQiu7gYfPOAADEC4A9iJbRHtEU1fBCXu6TnM/OZO5d136DJNST+zSqTRCR2SGeyfmUw86kLDVtHtKfEgJDxY0e6ZIRM+jz+HnJdQuEpYDCJi/y2tcxUI9YHUIMSrhuUgoUxeRlBJ8+1xYBbLGSS4Qi4i3NCta/spJO6EFgQ1oAWz0ubc0jPhiQ3pm
    admin-user: AgBYqukhABmdNREXK5MUVp+EHdJ5CfB+6MVMEkAbn5cmQA2L+9dxGMV7x9bia9Rfd+byGug/PC3yIPJBEuqimPmu2iMKzi1kxlk6M+pXfnzo0u5buhQaCSO+liq851Wuh2J2gNgN+EaHNSPeD28qAqeigUM5G4mbUc6eizsjMWWGlYN7jbP7cod4r6IPy7dQr5f+Og6zmu14sXBNzCfOP2iv/+cmKOfYASyaHnmnvJv4baQ41fuhLv4AOiNeBNci+hwSK/LLFCPAHtHmDCdLX2R9Bo5XOyP89A3BW5T1NPbHOZuxaZ9xkNqOCQzZWrjQ9UCU7PYEqfow4MoSTFXnJy/9AzasBPoQaF5lmVbbUZQV0M2n/6esQyQJGQr2IoZ58d6m2iWeL6dp/2NZQpZFdSS10CjSdoj3UBshup/6nIHuCzI6NEEqtUdiAnVTVwdVOQUKWb/4meBMMkS7n9SFqFWxf3EDo7suFDfm0ATh7ESuMyvCuIlKcL4W96WJ7uwCrkjYqACIrtF3RviiIIwheknXSpXBvUZR73N0WsePeZoo+lfoqAm0EsVm0kXCO8UQ+zakjCUyjoAmLBEvM7lk2YmlIVlqwRZF6PNbyVPfIS+g7HvglnePlPpe9CDoDIg4WtL/TWB6u4rakSkX+a8J9ZM4Px9O9aIFJOtWOBxD2xO77ujzR6ZLDrod8vY8Tg40VBAxHdiJDQ==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana-secrets
      namespace: monitoring
    type: Opaque