---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth-secrets
  namespace: grafana
spec:
  encryptedData:
    client_id: AgAccKQH/R70UiX76yThMtTsTCCVqAA9pUS7IxFLQOpMycmYBzN1sr4nkBoUkQY89WQjBVsaIri3FSqnLzMJCR69FsnjPy8tmFfYkHe4C6xyCpEAgDjx8SKX4/RzrArWXF9Jtc4ph3LloeSZZJjpMFGELP49SsY2rkzWUlBFemXs8DBkp/5F31rXEzvzmX6/l0YkPJT7h0K+DmZQMoEY4+hG+ft6eLELnmJIzvyDsTuhRrqtw5HzNQWKKsG5zlgByRQzIeHPfVUciGiEV0z6iH/8pc8YheI6nMBMKyb98heGXoJ1DzSfFKb2tb+hUndhzVFphEsLb2kgkkKSwBESS0eyX6qoPwy4BZNKkmEYP94M7T27ie2AlD+e63pVfWRZPir7XZfPDCXrj7nVxVnuq4nDW0Sze7baTcQDV2rONE3lb4jIRflWX3dZ0kSe7PTN7UPH/RdE91YSnflHZSAFo8Etm/cmp4p2k5+YIlSkajRDFvpncxwCb2Fg4Yd17SXQtrgxIHz1GKXCLLR2xrgvsyHORvfoWjq+AS0fnPtIQa31Qm7Gh8tMGAOcW51EEsTXybc1VaC4Gl8y3koXrbdMH2xJkq1bweAhgBAkEdEiZss/cTjuAOGndy9yPwIGlBy5twFypMp+jp7iW0U0tnHwigoTvSf3NG1wpA5LDCRLOqF59pnhaGUz10ekB3JvlNrihIiqNlbnFan5V4bs2faSqnJcGS4Mpnn4fB37aQ1qq236QIMjf+ECqeEb
    client_secret: AgCAQlw779kr81h0aWD3pAnZUP4pkdnqDTsuKO4rpA0u2UFoxoEpSmZA3Shx1ja5ddqkZudYCmNecOf2Xw8WLSCmhdQ97MQXMWpMGH9tyKa9H3+eKeWnFShwMGI4XaMFQJ8D0nSAYek+MB4W8/SymO0LmDwcVQXuwuaf7GS4I9AKILAEf3wXFW5h/Zhg7UQ2FdjTARHhdIQ3rSfLG+54kNkbeXOQI1qvawA1Pm3lvtf3dS1M1gCRpc0s7x3n4STKmJUBKF9g6T2H/xNogiX7/xLMst6njXN6ALj8gQl9f2IQWXWFXtoPUPd32sGt+lqjm+AdpxDngoWwHa5bJRUKRRodx4ylf0ViRHDpRASFCHZePPODXbqdv3x1nBW6IVVd8nbClXpzerlYnZ/cuAwuDmA0F19FFZxqnpM6bA1p0vmqgjAlJulgQVoOo6lZ8W3kkz2INqG3VhhYUEsK4x8Q/R+AFrD31n54k3uUHKw6VsjhMPzVjG02JlzKzGtv5hxCZm7dia00WoahRhmMYfDbBQ2AKk8+UCwPThBUMdWXkWX9/khJehR1/KZx9R4eqjsxRF2jTVkr3vGAj3T/VhSPp8ci9w2QIHpU8UQSo5DR9w+s+6gNLIqGhu+/zffoepxXIm9bUZb3fY69ggeFjOUwlU857pzxr4ie/I+p8NOUXW3OLNSdzpTCQMF70UcqnpN+P/M48obHQ5xO4yxjMlwd34e6U7UlkTQXLTgKLCFVQG5aa6vbblL4RskRndMfwqnLRJBm5FLXaCD/x4Ll5XOdNWO3J5IG389XuuV4AJM7PIPRjdYxWQBD0h/5y6Dc2CuVihd214HpM4Miu9/8YVCCEDEs9afO1nKxNzOh3AnkhkvYRQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth-secrets
      namespace: grafana
    type: Opaque
