apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: jellyseerr
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.6.2
  values:
    controllers:
      jellyseerr:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: preview-OIDC@sha256:9f3195998306da6548fc3b2420d114dda64a6e904f41e911168788fb410a7972
            env:
              TZ: "America/Argentina/Buenos_Aires"
              LOG_LEVEL: "debug"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: &port 5055
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: jellyseerr-config
        globalMounts:
          - path: /app/config

