---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/namespace

resources:
  - pvc.yaml
  - qbittorrent/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - filebrowser/ks.yaml
  - prowlarr/ks.yaml
  - bazarr/ks.yaml
  - jellyfin/ks.yaml
  - jellyseerr/ks.yaml
  - flaresolverr/ks.yaml
  - cleanuparr/ks.yaml
  - huntarr/ks.yaml
  - deemix/ks.yaml
  - navidrome/ks.yaml
  - beets/ks.yaml
