---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/namespace

resources:
  - pvc.yaml
  - qbittorrent/
  - sonarr/
  - radarr/
  - filebrowser/
  - prowlarr/
  - bazarr/
  - jellyfin/
  - jellyseerr/
  - flaresolverr/
  - cleanuparr/
  - huntarr/
  - lidarr/
  - deemix/
  - navidrome/
  - beets/
