apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: media-downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
  labels:
    app: media-downloads
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/main/downloads
    server: truenas.lan
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: media-music
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-pv
  labels:
    app: media-music
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/main/media/music
    server: truenas.lan
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  selector:
    matchLabels:
      app: media-tv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-pv
  labels:
    app: media-tv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/main/media/tv
    server: truenas.lan
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  selector:
    matchLabels:
      app: media-movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-pv
  labels:
    app: media-movies
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/main/media/movies
    server: truenas.lan
  mountOptions:
    - hard
    - nfsvers=4.1
