---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: /onlyoffice/PG_USERNAME
    - secretKey: password
      remoteRef:
        key: /onlyoffice/PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onlyoffice-jwt
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: onlyoffice-jwt
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /nextcloud/ONLYOFFICE_JWT_SECRET
