---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  interval: 24h
  retryInterval: 2m
  timeout: 8m
  path: ./apps/home-assistant/home-assistant/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-assistant
  dependsOn:
    - name: cluster-secrets
      namespace: flux-system
    - name: traefik
      namespace: traefik
    - name: longhorn
      namespace: longhorn
    - name: multus-cni
      namespace: multus-cni
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: false