apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  namespace: media
spec:
  routes:
    - match: Host(`lidarr.${TLD}`)
      priority: 10
      middlewares:
        - name: authentik
          namespace: authentik
      services:
        - name: lidarr
          port: 8686

