---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: _
spec:
  backup:
    volumeSnapshot:
      className: longhorn-volume-snapshot
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-backups
        serverName: _
