apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: beets
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.2.0
  values:
    controllers:
      beets:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/beets
              tag: 2.3.1@sha256:cc4975f1a0be4e238d29fe13c18ce37e08964af0d5ceb1811485751b6490bcaf
            env:
              TZ: "America/Argentina/Buenos_Aires"
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi
    persistence:
      config:
        existingClaim: beets-config
        globalMounts:
          - path: /config
      downloads:
        existingClaim: media-downloads-pvc
        globalMounts:
          - path: /downloads
      music:
        existingClaim: media-music-pvc
        globalMounts:
          - path: /music

