apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: docker-mailserver
  namespace: mail
spec:
  interval: 24h0m0s
  url: https://docker-mailserver.github.io/docker-mailserver-helm
