---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    server:
      domain: "grafana.${TLD}"
      root_url: "https://grafana.${TLD}"
    auth:
      signout_redirect_url: "https://authentik.${TLD}/application/o/grafana/end-session/"
      oauth_auto_login: "true"
    auth.generic_oauth:
      name: authentik
      enabled: "true"
      client_id: "$__file{/etc/secrets/grafana-oauth/client_id}"
      client_secret: "$__file{/etc/secrets/grafana-oauth/client_secret}"
      scopes: "openid profile email"
      auth_url: "https://authentik.${TLD}/application/o/authorize/"
      token_url: "https://authentik.${TLD}/application/o/token/"
      api_url: "https://authentik.${TLD}/application/o/userinfo/"
      role_attribute_path: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
  
  deployment:
    spec:
      template:
        spec:
          automountServiceAccountToken: true
          serviceAccountName: grafana
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
            fsGroup: 472
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-dashboard-providers
              configMap:
                name: grafana-dashboard-providers
            - name: grafana-dashboards
              emptyDir: {}
            - name: grafana-oauth-secrets
              secret:
                secretName: grafana-oauth-secrets
                defaultMode: 292  # 0444 in decimal so any user can read
          containers:
            - name: grafana
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 472
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: grafana-oauth-secrets
                  mountPath: /etc/secrets/grafana-oauth
                  readOnly: true
                - name: grafana-dashboard-providers
                  mountPath: /etc/grafana/provisioning/dashboards
                  readOnly: true
                - name: grafana-dashboards
                  mountPath: /tmp/dashboards
            - name: grafana-sc-dashboard
              image: quay.io/kiwigrid/k8s-sidecar:1.30.5
              imagePullPolicy: IfNotPresent
              env:
                - name: LABEL
                  value: grafana_dashboard
                - name: FOLDER
                  value: /tmp/dashboards
                - name: RESOURCE
                  value: configmap
                - name: LABEL_VALUE
                  value: "1"
                - name: UNIQUE_FILENAMES
                  value: "false"
                - name: WATCH_METHOD
                  value: watch
                - name: TRY_REFRESH_TOKEN
                  value: "true"
                - name: NAMESPACE
                  value: ALL
              volumeMounts:
                - name: grafana-dashboards
                  mountPath: /tmp/dashboards
  
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: longhorn