---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - objectstore.yaml
  - scheduled-backup-objectstore.yaml
  - scheduled-backup-snapshot.yaml
  - externalsecret.yaml

patches:
  - path: cluster-skip-empty-wal-archive-check.yaml
    target:
      kind: Cluster
  - path: cluster-storage-affinity-patch.yaml
    target:
      kind: Cluster
  - path: cluster-pod-security-context-patch.yaml
    target:
      kind: Cluster

replacements:
  - source:
      kind: Cluster
      fieldPath: metadata.name
    targets:
      - select:
          kind: ScheduledBackup
          name: cnpg-backup-barman-daily
        fieldPaths:
          - spec.cluster.name
      - select:
          kind: ScheduledBackup
          name: cnpg-backup-volumesnapshot-daily
        fieldPaths:
          - spec.cluster.name
