---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-backup-volumesnapshot-daily
spec:
  suspend: true
  schedule: "0 0 4 * * *"
  backupOwnerReference: cluster
  cluster:
    name: $(CLUSTER_NAME)
  method: volumeSnapshot
