---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: /vaultwarden/ADMIN_TOKEN
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: /vaultwarden/MAIL_PASSWORD
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: /vaultwarden/MAIL_USERNAME
