---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden_ADMIN_TOKEN
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: vaultwarden_MAIL_PASSWORD
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: vaultwarden_MAIL_USERNAME
