---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      version: 0.32.1
  interval: 24h0m0s
  values:
    timeZone: "America/Argentina/Buenos_Aires"
    domain: "https://vw.${DOMAIN}"
    signupsAllowed: false

    storage:
      data:
        enabled: true
        name: "vaultwarden-data"
        size: "5Gi"
        class: "longhorn"
        accessMode: ReadWriteOnce
        keepPvc: true

      attachments:
        enabled: true
        name: "vaultwarden-attachments"
        size: "5Gi"
        class: "longhorn"
        accessMode: ReadWriteOnce
        keepPvc: true

    adminToken:
      value: ${ADMIN_TOKEN}

    smtp:
      host: mail.${DOMAIN}
      from: vaultwarden@${DOMAIN}
      fromName: "Vault Administrator"
      existingSecret: vaultwarden-secrets
      security: force_tls
      port: 465
      username:
        existingSecretKey: SMTP_USERNAME
      password:
        existingSecretKey: SMTP_PASSWORD
