---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  encryptedData:
    MAIL_PASSWORD: AgAXhGuHa7YuQEhx3n6vaDNyDhM4Li9hKDPybBYrxY4ARW5fHsz8v8gsRMNIK+40tEZ9KCQkjHB8XzuzsfyXlEpCHvq4cu8XzUIrnBywWRf+PQFOZ7kIkeDToJ7XYpwZBGpedTjZrPTy6H3qq2vKdvZP9mlxf9jq8P/HcfuTMxmYGm+b6/NiaLTJ6QGc8OEqTzyAkFDct9OCqlPxzhq2JiL0uJ5CBEroFIeWdE5N826bGcADTm4DuR9B6XByTIHXe2rlXaqEBK+gXoQEvyUqH0ga3sZvL+3g0L81InuP4Ms+DHprMOgE3+pq5M1HXis5TVa1el6imb7/qChK0FvrYKWKErq7DKFJddfI6OLss1+SCKaj6nXjyFehNnRknwTfeHoJzQ8WFS4g0SH/Dv8xA7gV6sisLG+Y/4axfzcPWzH3yiM0esemRnh92CG+mkIO4Y02oxc5DtKqgB+4wCFfvD7KI8OilZKzMWTQfaVoy7FGWToLD+kpCJlhuxD6xnKYSLhxWcFtRQZRBpBSstbCVMwSsmnN9eTzSMFizbBnSdbxqwlzicy+QMlMYrICqW6wkW2qMCMjmfMJjfXZsAOuA9tp51/RVDo481uy/uFO6wo9XL9SIdXN6vKtNsboCG3EI7TqO20sF6YIY0RjvyL5TMRce1b8gQTlsRjIkWxM+brhjP9OWgmUOBCl8c0h5xbnVtVs0LuXACbY91Gf9nEMM+1Z
    MAIL_USERNAME: AgANKmq3wunMwF4smqqUGLHCh1EymOh6VWwBBKUDUtjus6lycAw3nQSl7E3zh4atXCyc364oAc6J4LOWIRr74jLn7b2jHnSzm7FmPOPkzHDp/6JtdmRBgTrsMPDqv021f1luQBFi1o+LDVbWndL/JUe8nqFtrGzePDKGVTrIAkuqdPqqLvVF/43vBR0gQ7brTNmsaapR9/sjBGsI0rvZNMHS7Tnaazl9kDnHE+2ri6XGYbiOa0Alm9jvjdFNTYdaFIY+wlxFWIgRs4xDou5+5xquvjIRyIcdtAyDNiDRBMr1HBYmEH/BvAdjVFa9JYATft/mw+TIbt326ds+sYd5a7sNbXQYGtVpWVU05YmJDLzBgXTht2RIbdy8yYP00YNucOeLrB01Tgk84EE8xuxsvGjZWL45W/HzIfhxYtHYZ2mEB3JeITv9P9Y5W4BUFKaaTJfwYYCSdXGCI4FY8W4+G1/B8EgcSUrPs0WTrZlnYwLdmVWRzetc0EQmlXCMBFUTTpuNHCjdkDGpmUafynbgVU+Sz0wuxYan12u6AigNlmuHAjJ65q+xEkDnfcjJYqc8YVJkP97JZ1aR9SLjxLEiBSa/KpxK5k/eoRc9cHk/y1AmliFQ/+7wOlwhaS1VEdxolxh4+U4uYf7JakWFDeFt3XWE9s7UnW2CP1vqWNxH7w5pZZZ1YzqoSKeNvGHzKGyehKVb74m6LAfM1Lu0E3AXK8KjwZFc
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-secrets
      namespace: vaultwarden
