---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: n8n
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: pg-secrets
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: /n8n/PG_USERNAME
    - secretKey: password
      remoteRef:
        key: /n8n/PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
    template:
      type: Opaque
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: /n8n/ENCRYPTION_KEY
