apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi

  managed:
    roles:
      - name: n8n
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: pg-secrets
