---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: thanos
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/thanos/thanos/resources
  prune: false
  wait: true
  dependsOn:
    - name: cluster-secrets
    - name: cluster-helm-repositories
    - name: longhorn
  postBuild:
    substituteFrom:
      - kind: Secret
        name: ingress-secrets-system
        optional: false
