---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: homebox_PG_USERNAME
    - secretKey: password
      remoteRef:
        key: homebox_PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: homebox_OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: homebox_OIDC_CLIENT_SECRET
