apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebox-ingress
  namespace: homebox
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`homebox.${DOMAIN}`)"
      priority: 10
      services:
        - name: homebox
          port: 7745
