apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser
  namespace: media
spec:
  routes:
    - match: Host(`filebrowser.${DOMAIN}`)
      priority: 10
      middlewares:
        - name: authentik
          namespace: authentik
      services:
        - name: filebrowser
          port: 80

