apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-ollama
  namespace: traefik
spec:
  routes:
    - match: Host(`ollama.${DOMAIN}`)
      priority: 10
      services:
        - name: external-ollama
          port: http
      middlewares:
        - name: lan-allowlist
          namespace: traefik
