---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: docker-mailserver
  namespace: mail
spec:
  interval: 24h0m0s
  ref:
    branch: master
    commit: 85257cede9cbfa1cfae1e8c0ece44b562d76dec4
  url: https://github.com/docker-mailserver/docker-mailserver-helm
