---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-secrets
  namespace: prometheus-system
spec:
  encryptedData:
    objstore.yml: AgBU7GsY1tKxN0k0TE/acuFh8W8R4GGJN7oydtzT3sZupKdfNFROwtuFHiNdHIkOqisOMMXXmS5ngAhFu09B9aPk2vGJrt+beEEV1Hu30KlSsyymmWhGp8zLJSTGO+Z17hngX0EGTYa06sfyNPDqXk0N/rWq5L+GgkOcKPuythPJnjQzKZk1S+tln1NV/x8B+jBKqt8mg+pQz3dktFVSO6CQZbahoiOUJpfXl4XbXDw3GAxAAIQSVU6r8EyJnM8Ac2IJu57xQMg3fT35mFbHua/waMvFM+G8N264tXFaHNiCZq2vrmpG1fq4Gd+2NnlSO7rhphfhtXWh0/WQG+alY9YSea1ieiGj/F/mZ0l72GsFrxXr/nv1c1jk0m3khgp+Z8bv3/sKbyrN19jGFAelbcG17LJZlGGZydK5HOUkeJFvri+qRJwSTX5aevdwzi3C0uZmNkqBN8VPyv9ZRfdQX3GCCo3k3ddhCJ/Sc6gou9oYRCfJFFoXLx3TzeI5fM/gEkpQ9fn1ghD2ToR4yqMBThO+jHSMu4ZbK5KVqb3XWlaDNo7XjOXKIr8zyo1WnRQHmGCRJbX1h9X3uTUyaYQZlulgl7Y+ajeox4MdMCNCcyUttF6weLLg+jX8pZS/ZO41kzGqMpYrREw8iFareWt41oH4Xn7tKP0/NpfyyoMcaSxqV7ljl9AEoH4yX2JGaD6cSmyftVfwwNnYv1wIVHUvkpN+8h05n/cp8ZsNn1UwbRR/oMVRMOv5IzO7r04jWXgfLTsDiDZ5RDcdD8NNJQZrYdydGhAqZf+fLVzh5376YHGyGngBSqp1Z4Rt6RMdkhz4JKS8svQLF4m6tyTIl07liRBeYshDy76yxUjARD/ltcDrSQAjiv2ouIZ3mszqeMoLkp9PQHK6jmXlOJUEZyNEmZhucHuFCFet+pBQUfyrVVB1SYLBbWeEipYZ5AmkMumoWG6Gu2opph3ofV5Qmsms44W4MfAF5yjbEnPRdLKmi/eECz3AXhXOaDJ0KiWSXQeDfJzNZMWdAmrEJr6udRm9lHFBuV6A
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-secrets
      namespace: prometheus-system
    type: Opaque
