apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: immich
  name: immich
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
      version: 0.9.3
  valuesFrom:
    - kind: Secret
      name: pg-secrets
      valuesKey: password
      targetPath: env.DB_PASSWORD
  values:
    env:
      DB_HOSTNAME: immich-postgres-rw
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich

    postgresql:
      enabled: false

    redis:
      enabled: true

    immich:
      metrics:
        enabled: false
      persistence:
        library:
          existingClaim: immich-library-pvc

    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          type: pvc
          storageClass: longhorn
          size: 10Gi
