---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-secrets
  namespace: immich
spec:
  encryptedData:
    password: AgAEb0uLDnO4N4JpJlXReBJHrmjFh+gKcLqMDYF/6DCBvW55qIjjOPZZxl5hkhe8XAnuHLwOy9YeP19cJjMHar1+FCbj7ZMS2TPlQyEj70ihacyMu4aPZd0ah1Caox56JK70XKqdO0OYVtNxJVUk4s/aZvq5qVpVPC0EKsj+y1vH7CVHbSmXT2ctZmZdquqEAScwnhJnqWCeEpLq4YyZWgVjjcg0biW4GAy0SBGB8H6Z2n+VfWoeNOZLZAJSL7NJJIITxJ72mhxrYNa9IS6SOw53nEY+thbhj4o74MEzmtABksUD1nANCrMe08sYAKaZPnE/HC31gah4/4eDlcuTVHk+/OvT8jwjY7vdBoDADy7q3J85ov0I8cbSRwiWus4aRBTxqo6TfviV2H4nSYqlj+lDTEsfD9wCGnWIR3TFS22oDeCq0TEgl/sy8ki5jkUzyEQ1/3j4Tl1GqVH251fXQdHe503KNb+950v3bdZ//tRlaX+nQhMHGk9UykCEoK6bIgdEADvJDo4SGDIA00GBYBgJ4vuMXypMC5Z8OjNnxkUUQla8njI00FgnuVItd3wnizeCxZPV2nZurjGx5QUkGE537Ma1niSfo5+bsd0Eurv4xrnleMSPcqmpuf7ifj08zHFfgnEZiEleF6ah/rytuO4aE5o+cLIvlF5u1SR8S1MzoD+PzX/0rBfHhTfHNQ57q9H5uZ9o/9d0Fcn6G1NF8uB3hYcQ2vEfREgBbR2MoPkVLxWnn4Fhhg==
    username: AgCKGQuKAYZSayxgYgZL/c9EOyADupLQFAUblyO/48RsQL/7VdJEi5MvLjsaf/OuPCVrFCvwUa8+7dPhhTZ0QqSg4cQktq8j/RGehNzI1e7CbOrnKDFNSrp3JpfkUAyS1oloM3QiWmFFmdQNh3uq9Kic8yNTSyQ1veqIdwDU7eX9lWIx4bP2zpOtzAxkTHcXra4EUHkMZSlDwLUA9d4Uzjru8oROdvX3ln1kbFPMnH5a1SwbyoVwkY+IjcUgOCt/hDl/BLToR/ebRPhjeO/C0bVZGGzN8JIedcf+ckh5dj7LX+NOVe+cKY2C59XvubpExtBZsHZZXHEyIxs3tgXS1s5MjGUdBMK80f0yjybB/qN/uB+CYK22LVG44sHo+Ecer9acKS+JHMj5JRDSoa+VLYZxptGcwZPZKaXDWPo5C9ZpTZQw4pJNbDu/GKJ8ujvi8VrYdRDQPnZ5PNoIa91uTBtjIIGwur5ujnqTXdHGHw5l5ZUBKR2e7+bZZlUS+8Bqq0GGZJjR2OD3tlOSTIOKWTFRS3d6z/6EIPNKwiwG2gagHdXzbVDQ2s/KgV0R58zDIYmth/zmA2BiRv6WUimqWUPGe/uSMZOF5s6cFbdM44IWVBdoSQB3QuqdSVbUxJ6E30OivkJRLa0abWQwhsxOK9T1/wE/wVwg4aely1IAHFhxpprGlLU2kx8e3pLm9wDmCSIfVxVez6E=
  template:
    metadata:
      creationTimestamp: null
      name: pg-secrets
      namespace: immich
    type: kubernetes.io/basic-auth
