apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: immich-library
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
  labels:
    app: immich-library
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/main/photos
    server: truenas.lan
  mountOptions:
    - hard
    - nfsvers=4.1
