apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: driver.longhorn.io
    volumeHandle: navidrome-config
  claimRef:
    namespace: media
    name: navidrome-config
