---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-secrets
  namespace: romm
spec:
  encryptedData:
    password: AgBjb/cABHxgZb5C7E1p8qjPixvkYFe7UFai3ot/SA1G2Nl/kLHjAbqKzUKEi+sX3YDS0T4JEoTjbztE4XfecFv3MFLXktb8SYWxfM9IrYGtqly0ErfKoxortJN4N367wUbPquLiZ6RkUkTuoFqRWW0Qbnx7YuiYAphLCTvziC1MF8BUc41TvazkDVFYHyh3XTGeBQ5BsZ0TaZhbBU5W4XZuc42btzSCJSuNhsRfyzcTwQniHH6CZ9UHXkRr4NvG0XeoiYtGwslq9+87yZVeRtHUXnV2RSW00wXoPe1xTdO/eXyaBMYC2l1scXZtxNHbzyY1Mir395r0PXcWDXO9i8Q+iIK3EIIlTMmc1dilh+gqNnigIqM3ms0OUyHr+Y0PTT1iNmiXcgce3lCp5IzdKdTUJTRMsxqwh8UcFzklPje+lDYNSMR80qJZF6atRDxgoV7XFv18rZNaLi0e3saaq8rD0/jUyCCJMQK3z6TUddavKmCvflUnZhVf8AT4KOku20W/f7c/7wdU6O594AiAiMZBVPHJUOjxG/KqutbDBsqxJy+oVSovITvnkpSota2PO4ycBW6iUyGOWq0FwaPhK1jGQFKUnX2jOXQz6yI5LBKm2c0ZV9BjgKVISKLIS9NIFakcQ1nTuNzEeZJIxkGmtzwn6fkOH2hu7IZc31Zzmm9sXnxziHxGo17K1OygVprFNrHpMwoLMIQsivxYWqKeo9Rbzr/kbCwmmK2QfcACo3cDNG4WqioGvHZktZasBDuQiXOUlglQ0vOlmKQGq3sPPzCk
    username: AgAeDm9+omfH8wv0pzi54uoSdkTHFslfQT7XUBQVLUn2+cckt2ZAGEnAhPAv/sRM6KVbFVrhFjDx084dOv1TgiAaHpQ3fXBqkpLbVpIona4BhxYIaC1PmBMTJ3ZytS8A4E1WEWkPxLVEo39I4WhkQzNq7gW/8T/KWrsHnMkwhtfNx9PZrrrYiyMCJyYdkn/4+svzt8VezVF3tus1/wl37wZPUwjGjX3cMP63pF08jradXwl+XUN3/UkRTbAT+eeu7YalQbBCqZnfdviiP1X//EmMJXk6A7ktSOz6PaSCoN+l3uizgoSzMtVtCk1n7Q6+38JseSPOwyA/X/xJpWl595mSmi4OwnuFXHv1SJc/DbNHb9LClpR+w+QL8ef9kDy0zUZPlHoHpv/fCnck24bp6EMkfb9sDsuX+zh+qPMuLoSpRJ2eUuVDzJjE6n2nVp7plCOyGulHsBpVRmvmVTVfeqF1KSKrf3gqybjcTzFeSB97oNZF5Hfnt4cjS0xTcHCnK3jtfDU6XE7Ir9CuovCxPdH0LlTZ7iKUd8wBTSXtCQG3ZF0SXq5OSmZ+oPCYiybA/j+4pZ1nmklNZBuhKwSp3juWmdHLUeIbPmLbHuCFmpfwqFgZRcLJQ7bEmJbSD5BlYDah7x7uVPOq2vr0BMdaFfetTzYXNKYImznztsjGl2PT3THXFsbOqhz82HF3x2Z+vejUDQgX
  template:
    metadata:
      name: pg-secrets
      namespace: romm
    type: kubernetes.io/basic-auth
