---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 36.3.0
  interval: 24h0m0s
  values:
    api:
      dashboard: true
      insecure: false
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        kube-vip.io/loadbalancerIPs: 192.168.88.100
    entryPoints:
      web:
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.0/8"
            - "192.168.0.0/16"
            - "172.16.0.0/12"
      websecure:
        forwardedHeaders:
          trustedIPs:
            - "10.0.0.0/8"
            - "192.168.0.0/16"
            - "172.16.0.0/12"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
