---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - community-charts.yaml
  - grafana.yaml
  - grafana-community.yaml
  - intel-device-plugins.yaml
  - inventree.yaml
  - nextcloud.yaml
  - valkey.yaml