---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  interval: 24h
  retryInterval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/cluster-secrets/cluster-secrets/resources
  prune: false
  wait: false
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: vaultwarden-secrets-system
      namespace: flux-system
    - apiVersion: v1
      kind: Secret
      name: docker-mailserver-secrets-system
      namespace: flux-system
  dependsOn:
    - name: sealed-secrets
      namespace: flux-system
