---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - network-attachment-definition.yaml
  - pvc.yaml

# Uncomment to enable the setup container for initial configuration:
# patches:
#   - path: setup-container-patch.yaml
#     target:
#       kind: HelmRelease
#       name: isponsorblocktv
