apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isponsorblocktv-config
  namespace: adblock
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
