---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-objstore-secrets
  namespace: loki
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: loki-objstore-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: LOKI_S3_ACCESS_KEY_ID
      remoteRef:
        key: /loki/S3_ACCESS_KEY_ID
    - secretKey: LOKI_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: /loki/S3_SECRET_ACCESS_KEY
