---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-objstore-secrets
  namespace: loki
spec:
  encryptedData:
    LOKI_S3_ACCESS_KEY_ID: AgBx2JyNl19jf+sy7HfvMFGP6xnmn0VXns1pW8QKFncugcRcnMtbSCmfSoZlSKuAjvlDOOmKfVeAmV2AZpRn4Bb9kdiGm9P5IvLBTl9UqbLEc0z4rLr1qNDJ0S46LZRjG8pzR/8fsYF8cdkfvYa6tI0AUvYzEFJLXZMbbuh43XDOC0l7rfU5W4JF1MXCA5gIqfVvYgXHelc1As3pKpes1Cu9aLzvhi2sPv5S9FraIGK/yNjiDoH1QQFUz/bkGpODAWVQCUtJ+ikpaombUArvKivIueqqToM2Nh2+32IJtNLUqzmNAfRI3Lok/C9iG0UwDdr1xgnRKxD3XAtoE7MUnpVElbLokZiSJK7BfdXMv5Dq8GPswMW6x4MtY0tjc9FwVdHvxbMaX0hJ6pAqg7AfaFuOk/nNGvemmIXb7suwsqhoCADTLuqpsN9qSlDK+n7gHDUnhwvM1S7wdkcQ0HO7CK2ea3l7wfht3rhH1E7nRbaZawnnLgHrAgFYPqSRmT4gY5Ju4+llL+XvAqYJ3c1bnujkKxrOsIyD0sheAG0H2ZzrLwIGRykOziSjYEvAxUF7K2ccUQV4iKaB2VvMet0anQjP6JSj7uWuhKx9kKTWugcvfJxjcd13E7KGMtRVGNj/Dtz1wKFiI5d8H2V2/1/tbeJnOT7QI8paglsVkDmc/bad/jCux42VYsVh+pOn3QtvsP2MXEpkD/luqhQD/bmkjuiAlJb0V7wEsDus+A==
    LOKI_S3_SECRET_ACCESS_KEY: AgBZU7Gvi43jDsP10Y/ggAQ9xuKDGIxJRvzYSszVa3YBr0JSIrRSx8O+Me37Ho5I6peuvdfgBb59noQdPBGQWTEGqgDDQ1DTMBt+1agQEQ3DjoYiEL/TMpNJmw8DYw+oUzAB4lvI9LTYMysYYPnT/h+z7Rexma0Dv044BCq0UiRdtaeCngOh1v34/+KDfVEEk01JtdUlwJLHW/ezfwb87Xgwp6/hGimGFXPqUlFm2UuFHUMhmLWlO39ngX6bP/HXlOIOkoFykFo5iWSGoibxljuHN2nBP1EhuysEAjlgn4WAN5LNl8hrcOitaamzcQ7nfUJugXRGSoGoNvNECvLkc+s5cUGgIEip81SSyXNil3qHxsSRhbH+KMc+uqFKijMR5tC48EHC3MV49/2Soi7Uo8ibkiq/qQ2HgH5qbVG4J0PK3WNWYxE/8nch7wG3Cdm71WeaWAe2cGN+W9KdoCbI86CDcexZjt/uqs5eT57yMlZoXZdPqOaOIGpI23KBIYWgRg1O24tyIwMPZpI6Aq0FnGHltKQK3Q23rb1lcQRElfnHqjiVnSaQSacT/i7iOKYqiFnhlsMc/OH6/neAiK08Zt/X8ZgPTVL9GLX/cmHcuLUJnyR/7+nD+wZukdodpUbj91riy+kPPxpHw2lNdwWFnmBRt0rDcCs2O1c90HgS45mjyWJxm4ZyTI0E7IhdPWnN4fHZknhVxxoo9jOVKj+gbyBKwQTGDGG1hNg1MA4FZVsHy3OsE897WeW2Ktec1o4Yt/LqeXWNQK8qxiuXzBcuebY7
  template:
    metadata:
      creationTimestamp: null
      name: loki-objstore-secrets
      namespace: loki
    type: Opaque
