---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hellbot-secrets
  namespace: hellbot
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: hellbot-secrets
    creationPolicy: Owner
  data:
    - secretKey: discord-token
      remoteRef:
        key: /hellbot/DISCORD_TOKEN
    - secretKey: discord-channel-id
      remoteRef:
        key: /hellbot/DISCORD_CHANNEL_ID
    - secretKey: discord-guild-id
      remoteRef:
        key: /hellbot/DISCORD_GUILD_ID
    - secretKey: telegram-token
      remoteRef:
        key: /hellbot/TELEGRAM_TOKEN
    - secretKey: telegram-chat-id
      remoteRef:
        key: /hellbot/TELEGRAM_CHAT_ID
