apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: flaresolverr
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.6.2
  values:
    controllers:
      flaresolverr:
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
            env:
              TZ: "America/Argentina/Buenos_Aires"
              LOG_LEVEL: "info"
              LOG_HTML: "false"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8191
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: flaresolverr-config
        globalMounts:
          - path: /config
