apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: huntarr-config

