---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: nextcloud-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: nextcloud_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: nextcloud_ADMIN_PASSWORD
    - secretKey: smtp-host
      remoteRef:
        key: nextcloud_MAIL_HOST
    - secretKey: smtp-username
      remoteRef:
        key: nextcloud_MAIL_USERNAME
    - secretKey: smtp-password
      remoteRef:
        key: nextcloud_MAIL_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: nextcloud-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: nextcloud_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: nextcloud_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-valkey-auth
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: nextcloud-valkey-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: nextcloud_VALKEY_PASSWORD
