apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      flavor: fpm

    nginx:
      enabled: true

    nextcloud:
      host: nextcloud.${DOMAIN}

      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
        smtpHostKey: smtp-host
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password

      mail:
        enabled: true
        fromAddress: nextcloud@${DOMAIN}
        domain: ${DOMAIN}
        smtp:
          secure: ssl
          port: 465
          authtype: LOGIN

      persistence:
        enabled: true
        existingClaim: nextcloud-config
        nextcloudData:
          enabled: true
          existingClaim: nextcloud-data

      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '10.42.0.0/16',
              1 => '10.43.0.0/16',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'overwriteprotocol' => 'https',
          );
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'maintenance_window_start' => 1,
            'default_phone_region' => 'AR',
            'instanceid' => 'nextcloud-homelab',
          );

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgres-rw:5432
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: username
        passwordKey: password

    redis:
      enabled: false

    externalRedis:
      enabled: true
      host: nextcloud-valkey
      port: 6379
      existingSecret:
        enabled: true
        secretName: nextcloud-valkey-auth
        passwordKey: password

    ingress:
      enabled: false

    cronjob:
      enabled: true
      type: sidecar

    phpClientHttpsFix:
      enabled: true
      protocol: https
