apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret.yaml
  - postgres-cluster.yaml
  - pvc.yaml
  - valkey.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - middleware.yaml
  - ingressroute.yaml

components:
  - ../../../../components/cnpg-cluster/normal
