---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: miniflux
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        DATABASE_URL: "postgres://{{ .username }}:{{ .password }}@miniflux-postgres-rw:5432/miniflux?sslmode=disable"
  data:
    - secretKey: username
      remoteRef:
        key: /miniflux/PG_USERNAME
    - secretKey: password
      remoteRef:
        key: /miniflux/PG_PASSWORD
