apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: bazarr
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.0
  values:
    controllers:
      bazarr:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/bazarr
              tag: 1.5.2@sha256:dbc87e5ce9e199709188e152e82b3ff5d33e6521a1b3d61e465aa75b4b739e7f
            env:
              TZ: "America/Argentina/Buenos_Aires"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 6767
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: bazarr
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: bazarr-config
        globalMounts:
          - path: /config
      tv:
        existingClaim: media-tv-pvc
        globalMounts:
          - path: /tv
      movies:
        existingClaim: media-movies-pvc
        globalMounts:
          - path: /movies
      downloads:
        existingClaim: media-downloads-pvc
        globalMounts:
          - path: /downloads

