---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: immich_PG_USERNAME
    - secretKey: password
      remoteRef:
        key: immich_PG_PASSWORD
