---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: ai
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: openwebui_PG_USERNAME
    - secretKey: password
      remoteRef:
        key: openwebui_PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
  namespace: ai
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: openwebui-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: openwebui_WEBUI_SECRET_KEY
