---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-secrets
  namespace: thanos-system
spec:
  encryptedData:
    objstore.yml: AgCQF3heAMtBG8qcPNvWDAH9CbANNKwZTM5wozhed2AOLSDlV4WL60xoRfaGkxehfq+a6pGef9yHQLT447zTIafTP6pnb9TYkf9vydK22QeNhbg88wK2iy7HJt5/kUp7c8lgFD3NSRla0nDultG3o6H8i/PgO0uXrteqEWm/0EV/F2/f4JxUDMptXP8Wr4qXgWut7bvpHC08OrUtpIcbha3vLfQ0Guey4F4n8y7PhIk9BAFwXUgSUVwX4RxHBacelYKhpc3WOwvwaGLu02HUbdwncD5PHe+j2FQ7IGcO6njx5s5YeR+xeZAIZf4LlYs6f0NkrOMMks2ibAFCjFVyK53jVq7X8ifmwHJtQdxsQWQod3QjHAv0dxtN0XQPxqXzd8nXhXypvVY+kypPW/mMecdTJpSH0RouhxFOq+/6sXA2VjnkRbYZam7ofbpNmOFgbxUDIVfNBNvdeHAmIqsz7nH8rUxKYyrpcrDkg2sjalIDFeDGnTUDQCIEjFbpgGgrc+7oVneCt0L8J4zTsGnSaVly5SYPyWQS+t81Aq22JWgbicdVUQAQgMM8Az+eWNktly43Sty8iMyEeHT19MMucB8nN+jfBlwtur71pG6jc8uXcIajEnZ+btiog7BQwKvaszBTU0kY7E8GspFLA2RtFc4picl07UEcMNzoFnsMTAm58TGUh0NwboSWfU3lKHk3pVLB9npqqX/GA1GK2h0JdhEp7110cdecVn3s5ejNDB2cDSijv3UCI+VXxTO6/usiqPK92+JWkOlBV5T+SBKyW3feCinGVoCW7zrtUcR8s+xjtEqH9ZS1n5KNdLbZx378wB6jAuwrkyo8zVtsvoBMNIII8xBoAu7A72ygp71xrIF2urSXWtansVl4GGcX5JjOkjEtJW1z/nk7oGBfVgajjrnbWmGBR2xaWMLyd2CnyAARf7PZcJGltEzX9fPwjUTVShGUCutbw1Uz3f9x0k62papSVbpO0KrUreGGcZXR6jnRvm44d9dOB9iEdn/xf2irNYOthKja1iB7K8400AFtzMK08apD
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-secrets
      namespace: thanos-system
    type: Opaque
