---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana-oauth-secrets
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgBOoDZFIbWAhUkl6tUxE3c6j+DW77wGqoFTWeZEbb23nsgYD5MqP+hO6YGBDkYIx9q20KG4Vf2qi6jDdU6mIt7scChhSD24nJ3aEBibxCURFeW1OYmJjX1zKtwxOlFGTCWnblj8MAm5znos2fB9+g9kkxPv4iaME2mES76f9WGKBnewsvx6HpyatKu6edqh09Qt8ezJrFNnCLIACL8SUfNsAHF7m24O7cOQs/WUMqWg30i80rm5Pn2pYhpkuSTq51hepcpTGuOD9rNweHmfOy/lr1y16n2Sh0RR9PBU5zRk0qrtvSwWyBycuPE9Z4V0C/cfbQcmyng/l1C5Pv0q4uOUpqYtCWJAvEuXiDQvXouSg9uhCjQDeNwLR2VZVWjNAa+6v4OoNLOIrQ3Vi7a4eyHZsgIRLnr7zWLELymABJsjepBV1vBwAWo44w74okGfwXXuJh5ufiNwCJKO2JAoRPRc/WBkZ6xv70r2JPsM9aHbQDtZVRukH0RcInGFQQaZMHdfxQ8baQnFmexTB8aDOFq24kG8V8zBogf0y3TAlTU9AWTgRB6Jarj3CP124lln+2KMeYvMs3m30c5+k3nWNWdnep/qxKjG8gYt7mJBuYWF/IlaGVp0babjMEji9KkHV3+3E+rpWRgMJoao219h3/PBNMpZ+d4DPjQ2oCOI3FDBYAptV+aTV/d3JUPhdLrqW8WcfzPZF3VpDgAqsc3wMd7LMViJ3AGAvZ7CxbRuzXFU/7VIlkgdRFA4
    client_secret: AgA9ShNgXl3ri3PzIWMfTOO32p0gLx/az0i+VlWQ0ByuLmK1vwZCq9dqD0+cxFPEqAh9fuDuGl2xoUggNfj3vniQOlohUkv/HZiiFR1RFELbbygCvDuTLYWAFlnGLnt0EeS2jx0GCVUgf+sPN0qbs6qq1ogF2bpGNDWvZwFw8KyvmLPfT5tKTIE0EOAsPYe+028csXdidNb9yIIX5Ah7KIQodMCBr4MtshnZN9hvfpP5piJcMihAdYnOcVAIODmJ7r5t+akNOPVTy8vbLi7imJ5bpnxa+5LhPDjT3ymjqHrq3hb6Nxa7ITo09m7IHMtAGJm7LX6s4ql5m3lVe4uesRbVGFB0NwfwJQrA0cjo36tROxZaRNYkoygXSX+9HrotMYPMR6AnFPooMSyZ9bymRvA4/Xs4lBoKRIpoOwCR7BP7Qf2QSS3i1GVVlSyOU9gu6MVhZOuxIA5TY3PuUkf3gjFVCva0+wGjWC8wjOxAjETuwlF2xCj7NhDoAty903McZkqAWvq64pSA5pnJFTC2qOFpTB+vswYkBcBUDV/2hMUVuqGf3ekIT7LzjNv7m8XWQQGKLgJ8pbiGUA93+7B0xqL3kJ1NtgZuhwTVB8bo7utHwzFV6KN3CyhvVoL6l9hBE+gVqFc/ZnMp6qRmVyZAbDVUkOxJbIVOfbjkYPTTdG4/2BuYh11SY8cLsdtK1BAAr6TUUW2cIe6z1uDg7TdUJv6qX5QYQ1VdpHY2UUM7NWLKp/CrVgjHF1Y/oegh4Oh5hk3GXZXJ9HtrRO+u8Qr0JF9475UifynSr16mU5wdiJifBYFqSLApkyqzAYj2dEJHz44lzL965XpJrZk7dkdKtjWec/wuKHzAzA1FAQLoH7w+0g==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-grafana-oauth-secrets
      namespace: monitoring
    type: Opaque
