---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collabora-admin
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: collabora-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: nextcloud_COLLABORA_USERNAME
    - secretKey: password
      remoteRef:
        key: nextcloud_COLLABORA_PASSWORD
