---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-secrets
  namespace: wallabag
spec:
  encryptedData:
    password: AgCGh6maATdGgp0zknGvjdt6y/XoMsykLjSYjgvskZIdCoetBYwwJcKA9l+flxP+At+43qXJ5bp7nM+iILlkVX5iaQ+wBxDkyODW9nlBeImvhO86dLeTq8jzLYEAIdz97sqTEJ2nEmjWFVXIInx7mQW5/U78/Hv7TE4Fd/Zw9ZRLvfSPGyroXFbFtpbzEnM1j/7T3ULR8cELZTRobpJ7iWFeiKasR7IxW4FDfCf9li64a9ajXWors3GAxcVf4PUl3G1E3B/n9aSWsngPxde5Dcte7kOcEXGeem407VbtRqAXHrlXlwrnDTcsc6cwIf/jCYYKNVPb3NAaTtV6QW1+Py2XoZkuHPc8GQqGZo8olDihZSD2DDnj7an1ufMUSKizZd9A7XO//qpumBoly7AMq0JTgdyTcAifw3JqnW2n0KkPHd3F3H/onb38AX3Z+UlWjR8cn8uVzXZwNIKFaLMnEK474PaB2w88BpYbbFNcGEhDAmeqopLW4qMS5AuSO6xk2YARl3mWr/R/f/6M5XYqVLIdFQ8FSkKC4vxrZK7DMtSc7w3v0bpqF8aIdobBTSlrCF/2A07naa3rBXUh1qp8J1EIg/UF2jD+eBwPFqjApC+J+hVNTBoqUD0XPmMtDR1NuJoXE911wleGYDnHsBGenjfRZqZsXkON6g0VmjjhusVkPwnBWhefKP5tmW+Cj85o+rOMT8XjgLsGQGLFcUtsc47EKzNC3CxajD3PMjwflpDmSQ==
    username: AgAWqWAEZOTutmtYNvigOTSZ6lPJezLuh1csmbj6P6IBHsiw9TDP3SgDVfXzLyq/xCruXGE28yEE32Zx7MrygPogkPCMy9NRQxSFO124h28kWEeMQuRQe5r2YRSszGAzIZNbOj17CU7OKX0YMAXOGLO0goFlZQthBkxXMsM1E9/lzhoDVHRgcYVkFnKLX2iWeTPF4E6vtFNssy37fZBhKhzVLM44sJdnjRD1PxdOilEPJYTLwSTUzYepiBJJcBQNNVa8DMeHdLJ76GDR/zsFztGuVhnfsRTPrs1hQYsYrwzy3o22T/KBrVRtqHRcqemx0v9HOmoJW/CC+heb534jde789jA2CE0gpw9fh9MReC18oiHt8FoPPxuQ3uvcF2cNOSBYucZgjQssCDg1SJggazUe6VQXqski+F580q+yrKNxOmPTXY9cQvZr+CI9ipClhVcXS7uVbj2DRq1zl9OOgImL+VlCBXN2wgcdXq1hPs8hBXw7hhxcjJwXkyW01LPboWw8ouGvdXkFCTl3S/15tHcnkH0J9JLhy4gkhVz+hGdj49d0RbNxFjf/A0/vHXy8oWbwWR9E9w/lGZ2UX2QM7cosrKfeG1/V0PPX6Iwv2DPHNLMPUsP1E2gpXC5qSUufruIqX6EQ3NWqDKUaSJXXCFu/NJ0JPdz9LU4b0tpPPBAa3e46khEmfNC7Elz0eGiT6L7RPimRz/41+A==
  template:
    metadata:
      name: pg-secrets
      namespace: wallabag
    type: kubernetes.io/basic-auth
