---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wallabag-secrets
  namespace: wallabag
spec:
  encryptedData:
    app_secret: AgAlyMyV6Vwz1KzmZxreET5NOGjcBcDtBuRwMIzzUOWbnGCMMOdZNNeVyvfL4l8DxBRxkHfQxxGb4DDA4C8tEzAtrSbSBpT/rRevjiY/joODbIHAmY8wRDujFcXEBbtjaSlljQUJ60fO3bLR8ToZvhNaAh3hgf4MRuTVdo9A9DJUA4qeU5EAMO2vZigB6lu2qQqHL1mw0MS8PcbNm5EmFXOk86AYa/svO+XM4t5mgJl8jtGmKICieCbJSv8H9E+XUvylZxmEZoMt4Tg2wfkDhweSFez5lIjz3RY8X+HwV1NJYtiSXKwyolwwAnlKainjU1QBrcNovUW1Mvuxj6l8PlA9GyttUwwuXKRPXRcyrdCVBsTzuhLr4/m1ghpACZ/rahhkW9ks6aqcsbcRs3HYaded8JWipZ7q0teEa0Jvlv0sUng+k+Id0xHVtxIXiLdjwnWxIYHVcIqSG826BxK0eJNWePya/RseXq19c6xWIkMdKv4HhZUBaxHvU6p8Clm7+78zeGk+RVNLuZkrFmk+jqwmCHRyl78hD8BZFeqYMVbFaCRO/YN4ga4mpuKCvBIWdUa8thjF/951YDjSa65k4O0MNjqDeX3g+/3nXfWbY32/Pzy9EIZM52Kjz4ztiDyomCAbvt95lTCVVzYxOaQXUuYlyYHprePcgp/QczidJTRzF7kKmrindf3f0QSilJEvJuD75WFAjK4CHEuszfnUDmk7GPLxletbEVbuM3mQ/SU=
  template:
    metadata:
      name: wallabag-secrets
      namespace: wallabag
    type: Opaque
