apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: media
  name: deemix
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.2.0
  values:
    controllers:
      deemix:
        containers:
          app:
            image:
              repository: ghcr.io/ametis70/deemix
              tag: v4.5.0-test-sync.2@sha256:bc0e578813e4e195df6814eb845b04f563a39d6651d422bb9f4af9e05ba979c7
            env:
              TZ: "America/Argentina/Buenos_Aires"
              PUID: 568
              PGID: 568
              DEEMIX_MUSIC_DIR: "/downloads"
              DISABLE_OWNERSHIP_CHECK: true
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 6595
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: deemix
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: deemix-config
        globalMounts:
          - path: /config
      downloads:
        existingClaim: media-downloads-pvc
        globalMounts:
          - path: /downloads/deemix
