apiVersion: v1
kind: PersistentVolume
metadata:
  name: deemix-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: driver.longhorn.io
    volumeHandle: deemix-config
  claimRef:
    namespace: media
    name: deemix-config
