---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-mailserver
  namespace: mail
spec:
  chart:
    spec:
      chart: docker-mailserver
      sourceRef:
        kind: HelmRepository
        name: docker-mailserver
      version: 4.2.2
  interval: 24h0m0s
  values:
    certificate: mail-tls-certificate-rsa
    proxyProtocol:
      enabled: false
    deployment:
      env:
        OVERRIDE_HOSTNAME: mail.${TLD}
        POSTMASTER_ADDRESS: postmaster@${TLD}
        ENABLE_FAIL2BAN: 1
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        kube-vip.io/loadbalancerIPs: 10.0.30.101
    # Configure persistent volume claims
    persistent_volume_claims:
      mail-config:
        enabled: true
        existingClaim: docker-mailserver-config
        size: 1Gi
        storageClass: longhorn
      mail-data:
        enabled: true
        existingClaim: docker-mailserver-data
        size: 10Gi
        storageClass: longhorn
      mail-state:
        enabled: true
        existingClaim: docker-mailserver-state
        size: 5Gi
        storageClass: longhorn
      mail-log:
        enabled: true
        existingClaim: docker-mailserver-logs
        size: 2Gi
        storageClass: longhorn
