apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: home-assistant
  name: home-assistant
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.0.1
  values:
    controllers:
      home-assistant:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: iot-vlan20
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          add-routes:
            image:
              repository: busybox
              tag: latest
            command:
              - /bin/sh
              - -c
              - ip route add 10.0.10.0/24 via 10.0.20.1 dev net1
            securityContext:
              runAsUser: 0
              runAsNonRoot: false
              privileged: false
              capabilities:
                add:
                  - NET_ADMIN
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.6.4@sha256:4d510e8826491e17049ede51d8c89afba28791e7bf7ba72ab8411e66e02255e6
            env:
              TZ: "America/Argentina/Buenos_Aires"
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - NET_BROADCAST
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8123
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config

