apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - thanos-objstore-secrets.yaml
  - helm-release.yaml
  - prometheus-ingressroute.yaml
  - alertmanager-ingressroute.yaml
