---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: external-dns-unifi
  data:
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: /external-dns/UNIFI_API_KEY
