---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-secrets
  namespace: cloudflare-ddns
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgB9Ua2qXwGBY3Sz/8H9SVpI6X3cQkGF6g+MqK2xXWvj/KC6hlbu9XDAyFfeI2sRrKEgfJqcVtuC7fju2xFmUi3AKEG7uugLSe+pzPyXKt6n3Ep6xNurKCmzT8b55jaLMaPkLcdSzciJwR+AofryqXISDAIIojzwdZTOUo1QOvsqxSJCyFCNVy/RoSickspEI98PrrEgPC8c6fXAypEiJH7NVErVT7gYK/jz9D03ZTNMMcMpWbs5i3kVNA6sSOgeXSFiV3D//2uyJsdn1XndWjGaPaLG0NUVhqn/RvCrMdoG6SvP9I7EC5OEz6FZlvc5g581uzI9LJT6A3pFuWFCA75LNr6LCXf9xOX8qmsy3p1Q4cb9wu9833BCv60oCO9YC/kq4XMpRr53zBzZipPZDtVfw3lrvtXT8K/ouBuW2I/8a5hArdOO0KtpbjBsdix2J6Azv3qTRI8DrtU28pK6SMeXKmjFsTOoIhvofL4Va/wFKdx3jX1d5dffSKXm3bYDWZCWACM9uDHmgoga44av2WoqwvGq9hNJOL+5bAMZubFAogI8k6H35xxwzXV7iFhUbbnmzXnAASgCSiBQRmrmm10lguRm7LkAqaKPvupZnwhgIyUllW3uDFKUTCsOA2cLaQFnWqc50YBOE05idsIh5GsiaM2cjiEZKL1Gx1GEw8DkHpZEuR1IlU5ebb0ktMvvIVXpEBWJgmrFMcwdjPOgVBwIFSiYctiV4pGibeNSd5WMBeP3jBrzlTxb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-secrets
      namespace: cloudflare-ddns
