---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secrets
  namespace: cloudflare-ddns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: cloudflare-ddns-secrets
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-ddns_CLOUDFLARE_API_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-config
  namespace: cloudflare-ddns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: cloudflare-ddns-config
    template:
      engineVersion: v2
      data:
        values.yaml: |
          config:
            configJson: |
              {{ .config | nindent 14 }}
  data:
    - secretKey: config
      remoteRef:
        key: cloudflare-ddns_CONFIG
