---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  chart:
    spec:
      chart: cloudflare-ddns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudflare-ddns
      version: v1.0.3
  interval: 24h0m0s
  valuesFrom:
    - kind: Secret
      name: cloudflare-ddns-config
      valuesKey: values.yaml
  values:
    externalSecret: cloudflare-ddns-secrets
