---
apiVersion: v1
kind: Namespace
metadata:
  name: secret-reflector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  namespace: secret-reflector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reflector
  template:
    metadata:
      labels:
        name: reflector
    spec:
      serviceAccountName: reflector
      containers:
      - name: reflector
        image: emberstack/kubernetes-reflector:7.1.262
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        env:
        - name: ES_Serilog__MinimumLevel__Default
          value: "Information"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  namespace: secret-reflector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reflector
subjects:
- kind: ServiceAccount
  name: reflector
  namespace: secret-reflector