---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: wallabag_PG_USERNAME
    - secretKey: password
      remoteRef:
        key: wallabag_PG_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: wallabag-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: app_secret
      remoteRef:
        key: wallabag_APP_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mail-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: mail-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: mailer_dsn
      remoteRef:
        key: wallabag_MAILER_DSN
