apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wallabag-ingress
  namespace: wallabag
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`wallabag.${DOMAIN}`)"
      priority: 10
      services:
        - name: wallabag
          port: 80
