---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mail-secrets
  namespace: wallabag
spec:
  encryptedData:
    mailer_dsn: AgCSIU9kf+jDkUxelBaPO0omtBPnwXjqK2INim347b/QasV65OdUSc7tZGOzaAbQwbD1Iwj9jeCDbn+T8YXQ8DXI3cK2Z7c6mg13Pa7ESJ5A3EkTYaAjf4G8Dnzx2iGVSlIludfh4vXZG2y83rL86TF1ecwmKvft4+J9NCw1/wQ0igorL3zEZdgw6h/M+oDZXlLI6QXHl1cXJgjfpkgH69Xj3yBilJlLSugxpm4gmxwcNd1tijfwQ1XxUd1ws4HGDyaF4deFg0KGQbzYrlY5B4cnwaM1IkcjKvOStn2Sw7KOtAyxIeW14gdmqCcQEdDTFngubUtNXF0Z3vmDWINlDu9kOir4BRtqu0+wMcCTJd0C1E40m7mPYFGxe6shaCx5K6vni8vtaqiw1VDmTB5+CiyPIeGdaDeABMKDnvJDWE0Pc2KO39v/2b0duYfAry4jmzGvna4SpChvd/E90RvVkdABI8WjCv5g2PVpKJLIal9eW6UaZLb/daiU9LUMfOTDBoeAtlE1BHK92xe9/5IxyaBqrW8ZTbtuTTuHX8e71oYnOaqiYdJ3Jtgl0XA6dh4iQBxktzQwmICn77drJkwR9xNW1Fa3WztXvQ7FpzBscYZ+mY97iTN8oqLNveEN9M9I13faahqHKuxI+Nl3DdTq3F3vZrvIFlgx0xxAJoQM1A0BuvpEUiVlTN3G38MLkyo9l4xyp+hPUgTw6YnW8YFJDtNBU2M5J/T+TudzGJqdXIiN8orNASHwJ7jLWN+ntPqeYMMuD7ZURyez7rne9g==
  template:
    metadata:
      name: mail-secrets
      namespace: wallabag
    type: Opaque
