apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-postgres
  namespace: wallabag
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi

  managed:
    roles:
      - name: wallabag
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: wallabag
      owner: wallabag
      secret:
        name: pg-secrets
