---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-data
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: wallabag-data
  claimRef:
    namespace: wallabag
    name: wallabag-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-images
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: wallabag-images
  claimRef:
    namespace: wallabag
    name: wallabag-images
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-redis
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-ephemeral
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: wallabag-redis
  claimRef:
    namespace: wallabag
    name: wallabag-redis