---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
  volumeName: wallabag-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
  volumeName: wallabag-images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-redis
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-ephemeral
  volumeName: wallabag-redis