---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-secrets-system
  namespace: flux-system
spec:
  encryptedData:
    DOMAIN: AgAn+mjsXOPnlcan0w8Zq53nQzBVgYtzkzhHozV50hjPBQHB3R4Np5Vu4CI6VD1za62/DXEv5khYR9vZrtv+80p4JbFQfvSP89QqZ4KCmviVoXr9tjAevgk4LjCqIK8r+31huzYaE1I7SjToFEbXlUoWK7YoxXgejiGKd9L4WhpXxRcVPq/ACPeNXU/M4bUoaVT8J9awbJ8Hfnxfza6HxukJHkWRS/sjkNMXdFU9/FbDFQJk7/2OE4e65fjNUbze6c2nl6JKLNYAGKYmDhSTiku95+kg2QZiijv1QKewF3ja+asEOAbCXALub7KEObj2VWvcPCZQ+WyP5LmiiutXTUrXB11iZGD8KZWQ0IXw3B9PWA3TMqmG9YFCVYbt3bOEaZQXXquwXD3pGgb3gLoYdOdy35wpGFYbFQw4g8o8Duweyr0ZrWUeIVRzxBmNxpRLK07DmeZRaATFcrPZY0KhbiXHpfF7QAO49GoIzSHEgdigfV//rwrYIvtR3wkCMnt2OTubu8yxISZAValluY7F7zyeK1ubagV3jYS+0HRPDXirNw6XPPCEXbEbLlIQUnYa9W2G2SG+EWNwAXj50x78LGV71HiajzrhjKMUctHweP24M4f6flaS+l1ZeR2Q6KEBz8pdRxgwjLKxJDeXBcIm5f+Uafaff2YU245069gvcWo0qUdZzkjnVumLvWuXJs5C6mFOlfehQhoo
    ZONE_ID: AgCTGhK2JvJzijyx1whvqJr/CV4cfyr0gThew5m2U93bVK/u8OH4Sde6uRijVXmzWGt5rLHjeiBaxwWxA9VR26tlWSgSiPTZUJlI2fLxQ5Qj8sJO6pzfX4HJxiwOxd5igB2WMxRW2NPXsCeImF4/SLEL9Rf3QkZ2yRcxiB291HRoxRdpJw0SUlyHunhCrvjhNaXimW8eUsKU5/67U+WcYKKbDFBPksrl1Z/n8yPeHJyMQDhriblVMO8KeX7IzVbyx4ElQpSMPMwOx284qz1tZuSGNe2YGjlKgtnsfbpSvRufhoqpsE7GUoP8XAqUJEjvmNd/RHkakQvB9Edfg5bd6ip/kljt/A3X1ekQu38VXwl54qXf12dayVVp1Pbz/jMwAZN+ApDyW7DuYhtTrPhC+NR82oal0Dq7EF56zdS8O2Ef8yXCSc6V7v517HZLsDHhx8JrrFg8oHDmMG3zeSec7+jJwLtTkMc09wy0sFXXvg+JxparqbtHlJ3UiCysk5s72Lm5q9InGSntMYHXCMNFAaTPQAi0YXOs+JlRKhK6MkuBIjttEK0IkQnuud0MFRnrWV1P2754ASh1f4XizQMas8D0oMjaUhurQQnJsWBuMMwbxuHl3+LYmVseqc/8tawq5jBjAEcl6q6Hpaq6NsVzmTIX/6A5PwQo7wwCEf814HomeicZXY+6mDwkAGC1uLx//AUTFSV38WqDDclZOHq+S0seH52d6s8iPuI09GefIiqU6w==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-secrets-system
      namespace: flux-system
