---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-secrets-system
  namespace: flux-system
spec:
  encryptedData:
    ADMIN_TOKEN: AgBWEOlqQ1QxA1mJZQ5PoDOKE894OgfPr2XWpJp9kcd9FoL1vtlvRcpYWXdsqMuAK35024ngQAQYIJUXfaIjtb7AydXAaAyv5sUatBT5PGEHmzqJWz73GrrSqKe4QfZ53ZDbjhcLZVOli9GKZx5qfPFTYuXnZmr3OoYeDhQQMJEcureF1N0dUTWW5UYCnBhwmWDutjBC/FwGVEGELQSUMc+GLtNBXVcoJxNRihmcy1sqd8+mpM9LovLbVFgfxssl4VTjUK/qQrGHw9Bvymf+m3nodKaE41YyJ9LmA1H4jTDfbjumsWO4Y9/jQg/F320IAIzyyiTKgro0WcBZJ/5DuAq/z5N7GxsiZsB3u9Bbc5G4mKOVcybTKwMPTsWjVjGODgOLnFz/rrvL5OUVlvtGmqaZ/0ro3g+xyBnJCyWuXIMPcDrS/TkqRWI7fh7i6PD/BQrno18h8ahpIZE6uFC6m2HdVdoCgY/7DFqMr4Lw51ybqLQQjVfD9V0QhdQ1ARBPYeScyTKx5/VnFOxmcUrg7Ba0v8bU5ZBtK/bCBpcIc4XpGiwHNm1S6i56ghdVicunYwBDxkpjodiklrzfF4V7Zkxv3IkWXXmLRuOdYoxTrhkEURhtGxiDrrbe557JZLy4bcLh3G2F4OuviKxso6hhZxvynYL6Eb6JVhp+QH6rR7VtMoZzUoM05LFKdhVA8Q1DqCh1y5qTMYSG5Gee22TIPnQ4KjjweKwgdjMs5e7LevNxYhn4T09AZHfc2TceSaCMiAA/EcJ1ftr0jB6E79EXKZ+lkowA2yOy4suinWA5Pc7uZqwCm+tNrp9LOXH5nQ+jwVn4VNbAfo9i0ZAIyLbD4BRT8KYyhkDAwcVojZa2ix7Oq4nYLBgEig==
    MAIL_USER: AgB52A7iK9iVIR2KCDdSCV1mPbtA+v6lzTfvBEU1Zkbqi27eclWMVvDgHakf7YMt/QzTc0o99ESglvzJL6pHm/eKJQCs8IFPXcpWjkMLEl+QGUjmGrotWQp7bPC9IGHx2Xe4n8nyWg6b4DyCdie3yIFh/0u79Ys/SoP4gCwUhMgh06QrAH1s8j6f/6I9kv77MvzPVjxsS71ecijuDPCTEDnpvl9+j6SDH1ZZrZOJuqcVaOSmfWjMNwas7exyRcbo45sUuJ5vHanKhSM60ey/4zl97Sq6cBnk2/bMvkra2XI1ba4TKISEUPiNXg94xMNtk5GbJexIzQWHJ3wMKg7kqWApvMB6uDXpmolkSDwzYsJ7AqJy3oCnADcYDajgHyINGRKrAdiONvtkdwiN/c+eEzk7Sq9DLIDV0Tc//AoAgD9Oez4/akrKeA6zT0mkpzwsyy+Z3G6OIICEkYpAvyvTsIXupvk08kNT7PxWtiayRMZr/630LaHRHrXhAT1If5a88GVBru5PPi/5/0FDJA8O8ibaFCF5wLQw0NC+31caIoLdBLE18vzn+EIs10i/iWRQwcivL2TyNS7+Lt87HxEz+bVYHL6aAmUyygQqYqyqnIUIkOYOEIAgX/0bb5LF4uuSltAM/cJSnXmBCwEBbHxjEX8KbdQITRmjK7RuAchufElbzOx+rvPUKV8K2XTnwrRrQbUMDVj+dss+fcml8wcug0KG6Vxj
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-secrets-system
      namespace: flux-system
