---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - objectstore.yaml
  - scheduled-backup-objectstore.yaml
  - scheduled-backup-snapshot.yaml
  - externalsecret.yaml

patches:
  - path: cluster-backup-patch.yaml
    target:
      kind: Cluster
