---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volume-snapshotclass-crd.yaml
  - volume-snapshotcontents-crd.yaml
  - volume-snapshots-crd.yaml
  - rbac-snapshot-controller.yaml
  - setup-snapshot-controller.yaml
