---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secrets
  namespace: romm
spec:
  encryptedData:
    client_id: AgBDCkFasXQJILlwlGMLnEZdgwQ/XI1uof5qEjvqZKAXvHExNXARE6HlUdr3BUziEZWL2cvFSfaN7V7P2bAbPSvkUsv9ALUnzlUlvSLUr2H2YFBOBB941Zxg087MPjxj5Kl4pSv+E0Xk5d9wq35l2WR1aM5JzbDbp85xkHH8tnMKc+hPSOHdiO32sxa+BwfU/tEGmZ36f6FXaQsble70CRGZB1uv9kCyj2n3YVqaGRSKGluJPXmE+3levItnBKryDwhpVl1CXUl7i0QhV6uIgDyYXhzuIEu6c9RCp+c1PrC3VLB0tk9Wlg1w/on/FLVCdDdHotS33Fn2KxYNVXpFP1Oe53BWwlYEz+h5d5aOA2JGbma/NYkv6/APuqFf7wGGzrlvlGpqJINNW9pgkVaPRc4bVKDxWSJVpUSOPsf3vDYRHXIAMMe782Iqi2UnvtLpYbwT3S4aaMNsVVfNt7EnQGGUKa5Ex22trfy71bxuW8c1e7nBe21VLUFcJpD8MUbA7IVBmirWCajxULhe08ZOExCENkvb2iwTAQsrOPuN5hnZkVhxqeu3dZJA+hwngytSuUyJg90EbEnXYu7+wVEAFmLJS1i4Hhv9APfAWzxdm+4fJnJWR/zzwjUvrQPzw7aa+LrpWMTbevcFgyq3dXoKT1Pe5sJldaBVcqvnWGjefgXhnMLdAsui3zSweXKeK1O7h0X3SClOlItDO44tR+5lAVAIMsSOm+1gBwq1LoZTDnaOm8qnAS9laKJO
    client_secret: AgAr/jpEkJ3Qz4rHMfUkuJKTz7oHDuK5lLZIWBcjn2CKsG+VC6TfJ8pXb/6Cn7Vx+rBvi7O9/T7gH87KiABIx2PyKOPIGKF54qXIkGI33kmIM4cXVvVhX8eE79InroSSSsnImXibPBNwy3qk8L7FMwpxKFfQrDAshhzr/zEREKayxjEeYQ5D01nxeLQe3R7eTzlGjY7WDp9S6GHTPOTe1Hx7Cpgt3DvjhayHy26Yed+KyX7hyf741NZohFN8Xgo/ScQDWJstRF0tqy0+vDcgyoUHKcZ/3POaSuzqGCnH5+jhbfdp1tBOMDZPwCZgvzg5Ioehtx3uUd3tUEfKJ0jTP0NtBLFO6FuSwUcGneHa12Q0UbYbnX4b3yBGvI0FNe3fhIRwZl88sRtXRONI58teJ6Pfg2d9RFY8jFSSunph2H0hGsHLv+x5ZcqbZCK2OD9He6DMiFvXRbGn9M7GH/G4V18dqICXBXfLj/PdQwRNePBXS3O7/JRySCZhB/07j3MGSbk5rDW5Mo9/zrhCCTjuVkCqOo7pen2WdqU8noFDeBNbcXaDve9wfOkpzxDnFcEXFFHpyM7QP7WoSWU6oBpcjqgS2dXXflBgUJUlCwtkyG1wn6dRyLC26WM6yJVpY7bo1yQeW0kHI3FFI/qpbJR5tg4X43TQkHHeotY4iIjzzFJDOi0LiDIzss+iSXohad4xpkQF7BV9iKWMx/jzcG0Ix6vejgKx8qRZxoF90epd7kxjXVBiNJbWedK7x2xzC1AXT7t3Hn+XXKr8amiWPfLpNUbYhiTASmIco63ywy08eucqby3XmqGtIVugjhbhXjb6fxznh2bj2aA4mMry1+s/oc1RTYu+1amLoa1fOzLO8ya93g==
  template:
    metadata:
      name: auth-secrets
      namespace: romm
    type: Opaque
