---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: pg-secrets
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: romm_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: romm_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: romm_OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: romm_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: romm-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: romm_AUTH_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: external-secrets
    creationPolicy: Owner
  data:
    - secretKey: igdb_client
      remoteRef:
        key: romm_IGDB_CLIENT_ID
    - secretKey: igdb_secret
      remoteRef:
        key: romm_IGDB_CLIENT_SECRET
    - secretKey: screenscraper_username
      remoteRef:
        key: romm_SCREENSCRAPER_USERNAME
    - secretKey: screenscraper_password
      remoteRef:
        key: romm_SCREENSCRAPER_PASSWORD
    - secretKey: steamgriddb_key
      remoteRef:
        key: romm_STEAMGRIDDB_API_KEY
