apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: romm
  namespace: romm
spec:
  interval: 24h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 4.2.0
  valuesFrom:
    - kind: Secret
      name: pg-secrets
      valuesKey: username
      targetPath: controllers.romm.containers.app.env.DB_USER
    - kind: Secret
      name: pg-secrets
      valuesKey: password
      targetPath: controllers.romm.containers.app.env.DB_PASSWD
    - kind: Secret
      name: auth-secrets
      valuesKey: client_id
      targetPath: controllers.romm.containers.app.env.OIDC_CLIENT_ID
    - kind: Secret
      name: auth-secrets
      valuesKey: client_secret
      targetPath: controllers.romm.containers.app.env.OIDC_CLIENT_SECRET
    - kind: Secret
      name: romm-secrets
      valuesKey: secret_key
      targetPath: controllers.romm.containers.app.env.ROMM_AUTH_SECRET_KEY
    - kind: Secret
      name: external-secrets
      valuesKey: igdb_client
      targetPath: controllers.romm.containers.app.env.IGDB_CLIENT_ID
    - kind: Secret
      name: external-secrets
      valuesKey: igdb_secret
      targetPath: controllers.romm.containers.app.env.IGDB_CLIENT_SECRET
    - kind: Secret
      name: external-secrets
      valuesKey: screenscraper_username
      targetPath: controllers.romm.containers.app.env.SCREENSCRAPER_USER
    - kind: Secret
      name: external-secrets
      valuesKey: screenscraper_password
      targetPath: controllers.romm.containers.app.env.SCREENSCRAPER_PASSWORD
    - kind: Secret
      name: external-secrets
      valuesKey: steamgriddb_key
      targetPath: controllers.romm.containers.app.env.STEAMGRIDDB_API_KEY

  values:
    controllers:
      romm:
        containers:
          app:
            image:
              repository: ghcr.io/rommapp/romm
              tag: 4.5.0
            env:
              TZ: "America/Argentina/Buenos_Aires"
              LOGLEVEL: INFO
              ROMM_BASE_URL: "https://romm.${DOMAIN}"
              ROMM_BASE_PATH: /romm
              ROMM_PORT: "8080"
              DB_HOST: romm-postgres-rw
              DB_PORT: "5432"
              DB_NAME: romm
              ROMM_DB_DRIVER: postgresql
              REDIS_HOST: romm-redis-master
              REDIS_PORT: "6379"
              REDIS_DB: "0"
              OIDC_ENABLED: "true"
              OIDC_PROVIDER: authentik
              OIDC_REDIRECT_URI: "https://romm.${DOMAIN}/api/oauth/openid"
              OIDC_SERVER_APPLICATION_URL: "https://authentik.${DOMAIN}/application/o/romm"
              HASHEOUS_API_ENABLED: "true"
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 30
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
    service:
      app:
        controller: romm
        ports:
          http:
            port: *port
    persistence:
      roms:
        existingClaim: romm-roms-pvc
        globalMounts:
          - path: /romm
