apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-roms-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: romm-roms
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-roms-pv
  labels:
    app: romm-roms
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/main/roms
    server: truenas.lan
  mountOptions:
    - hard
    - nfsvers=4.1
