---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-secrets
  namespace: romm
spec:
  encryptedData:
    secret_key: AgAOlSxNf7dwwe7467W+lieM5BuibSdNGy6nk7CTb0GDfGdeb/FbaaWeQCynZSvIbw8vNb6DRq4aB73gno5nbMzYnChN1HrYNaPMupflCPmSmCr7D+OO6MDx05aEkItPn0CMY4WjorgNLAwD91Iv2/Cj7bBQhhZKoJXK67o1Lw5EZISmny9L7icA06iuZg3cBon6u7aRhKbNbZV830r5M1i4xW64FlII/uhZafom8Iu9ozh/9VeNBE95/ewrAYIsHzLXNyr4KDMtQ+CTUPNmoMM1rl8WHTISymEfP4bRldDs2iIhArQUx4j1CO+JUPB3BgSDCFCoC7V0oLE2AexAxjK56F728LUMPwEMBNcb6anWL3GbnFxkt8UkD/wpZ2zmMQOSrBhiZH5ybW6vJeA5wGrPcTLnjkLUXGLfYidf/GWLFSwdC2Z1W5OdYk7zdfyBOc8os7xkfmvdp57Yhq/Px+e4xuMkvDAOBp59eXle8dtMuUUus2M6U2AX4OpEBIK7WoFq4lqj01DUj7Ugi5CDkQfG7+e4cJeldsBsXRADPvTpqx9wTImrd5vBgt3YTp/uQhrz0+pL1Zpsky49igdurl8u2tVqNAJcPR7M0ghawvAGhL+eJgdf85RwOh98b1y66AMTnBd8YfDinFlcDuiB77r35HHjXvcEAV161ieMx4dHI1iM4I7nOp3E3xS2l0JoKGhSaUHRUXapzBEe7GYi5Bko8dIUfq5HmrmIx+XXlFEawig+hAUqggnlJivsIzbFI7WyLdvdJp9yiO/iCNjktXEk
  template:
    metadata:
      name: romm-secrets
      namespace: romm
    type: Opaque
