---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webhook-receiver-ingressroute.yaml
  - github-receiver.yaml
  - github-receiver-secrets.yaml
  - telegram-provider-alerts.yaml
  - telegram-provider.yaml
  - telegram-provider-secrets.yaml
