---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-telegram-secrets
  namespace: notification
spec:
  encryptedData:
    token: AgB/hzUrembJFTU9DWFHVuJxJs7DJ4N3U7IMSl6zpf0URCbWtEdId7UWdqOHdDw9ZssJc6KjYsBKpLmwRm7fx5dPSB1KbKusZSxSuB39RJoqhHEKBAMhDjfe3IcP3hLnAui0Z08xpqgccWZr9NuWB1wX+OM0mOaicCbFud8OlArVJi1OKU9+lH1+EVcinZo68tldH6peImZJmv3XJPlxuduTD8MdFRDGoK8fHP+/iHdycgxfgKQ+MD5Va3tNYIzZy8KhZKkCPkIJNs0Iax4h74ANK/wl7OslD8411Socjn0gRRZsibyZCgdGgDoHKsVtf2dZHUsP3xESPD1IpTvfCe4/cu6n7hr1VLreQAiL1/1vBXF7A5/KBvpIDZnRsT//pEbpFjIvTk+/WHNlK5XC1UXM0BzfE6c3odIQV22MG6zUMaOxc2F2VM30OBlLYd/pi9WrPOEl5ls2CGDUpoCChvLEO4toui2prcK3OZCfg8CsQ5Wk9ULTN6ys/8ghkmOk6PKR1GZ9C4rxGhlCCXWFlfbrujruw8XINIYx1GCVaJ5TGtTsAGH4aWZbS8rBfekHIPEifkiCXVUKD9LbYrlMj3AqhmFypajD9Tj0XdS8/hWhPnHWH0nfI0kuZA4YQDFB8il4amAiaQMQ24FkuO+K4krZyzxYPTWqQktgAZA/P7vVlMg9nLN7TPr5rozhkNlxDepgTQ13W68PrjF5FrO3gnw9g/eoj8c2G3Hnjc+SHQuDVUhaT0tCudT33G/7omDk
  template:
    metadata:
      creationTimestamp: null
      name: notification-telegram-secrets
      namespace: notification
