---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-telegram-secrets
  namespace: flux-system
spec:
  encryptedData:
    token: AgAII/9/A/ps4Kur7vJeAGzW4dvcKddY9vExifRFzAWEZvdsuNwJ5ss/k81v0hqls9CVOnZIsjiPtzgPc6EjNKXXQOsjV6g8Q0HnxP/FHN9vT4x37nkTHKPB2GGF72JUjDzt8LdMVEo4VyAzwq7jnWjVfVdBrtybjt8GYEJq8Slxd8LhtqxrP9WEcIxQHRB8bHtlsiWGayCEO8tCizBEEJ2a3FqBQohs8yhX4YykIXhSk3zCau2MVW0Awy3WBXqUi1zg7opThe27NS3hqoTb9vZ/vu+mkY4o7SHLYlY9HWYVibOJVzByzkRvYM45UnTAJQ5K+YpA0gfyVfPL2y3MuZTn+vBp+2/UgSVq0ufkEBGD0vzXmxfYyPye4xe6qfonqg9/5YsAb722E5Bsci9w35dBgeEhH8qsKeTJn6qH9U+J81DUAH+MLqeobGV8RGYhqD1wsxzcKSs+Zh2TSp5/ezLssT1/+AOuM8Z+/E2be4fQha1Pfj1/AEQe4foPZPjUJPtMGYtyF3Q+9eLLb8Lu70yz5pLMUtdBSrJ+b1z2XVBq3T14gNw5Li38sOXqhDwORp3aDJJpJUmzwrSl2SPEXFg0z8m+906/6/OwZyWnnYDIkHKGuQ7kdN07FXSSQeYtUkGBhrIKQbnSaS5f/OgTrTK7n3h/oBQHAHNgx3QFrQLDWYEtvYHcH5EDOb/1UUBefQMPqy4h+Z0g6qL9/QFWX5377e6ORt2++9/5lrTSxicxfbJ1ljL02/a1+9zvw1Mg
  template:
    metadata:
      creationTimestamp: null
      name: notification-telegram-secrets
      namespace: flux-system
