---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram
  namespace: notification
spec:
  type: telegram
  address: https://api.telegram.org
  channel: "-4934295929"
  secretRef:
    name: notification-telegram-secrets
