---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhook
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fluxcd.${TLD}`) && PathPrefix(`/hook/`)
      kind: Rule
      services:
        - name: webhook-receiver
          port: 80
