---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secrets
  namespace: flux-system
spec:
  encryptedData:
    token: AgBAjaXszSZdtCrkqjsICPCd58LBgSJsQws64Cw5cfN18EXEInj5bRFvr8X7YKm1GxBsyxgomN+op3cmZSDUqKdDH9AobBoFT+MYlZlIaKeYdY3EPCpR89ZqWEgUDVPFpQvsRNfW9cz8iiMc0/8CqOxQQxPqRg1Q4KwYn1nQv0NKv3xWBlqbGduh5r9saltaGrtwcu8cpE7xyjM3bix9/osHHenePk7T73F3o5WILJQw+yRLupwKkr+5HQBBoqtosPSig5jynZHGT1rhXzIpTXZ7W8rD0IOFNNGBTR/JjquTVP0kvxBgkLRvngq544432ixcbwtfsoU/YTnwL/l6cHaMQTveMJOQ90k8WxB2xAOYdabC33LG2fcnv9UHxmVElgdN1Ai7g4M/8/L5vHB+5FNWYCq6RwAhGu3fHh2cfNYR5QgSRTrrJQVIAq2HSptCY6BdrDpIVzJDK3cp6FbB2TyL+krhebKwdAcHL8dCUR2cMl7c4raU1Hjsh5n6r/O4OE5HBYcOG+9Lh+iH4FeQUr2M7wsh/MKs/f4y4FkhDwQOfd46WewDxqkoUupXKB1dBKS0kaUHCQCPreR2YzKwVkkLHThPPHuRAj4rzpFTzOc4+nv8D7an19IMbiHsJGO0b9jx6TwVPeBQOAChXm9dOjtrD8Gtk31yeNDhAs8xyrSl/Ojm4k8kGsgWTf+z2s9Hxl/qzp6lwKI5ofuZnSsGA6ZNQ//HGEHAAlpTNDaEsXU0NbX1vWj0uoEPQbAM8X+fuCs=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secrets
      namespace: flux-system
    type: Opaque
