---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-github-secrets
  namespace: flux-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: notification-github-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: notification_GITHUB_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-telegram-secrets
  namespace: flux-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: notification-telegram-secrets
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: notification_TELEGRAM_TOKEN
