---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-github-secrets
  namespace: flux-system
spec:
  encryptedData:
    token: AgBAYuj3evn06m5AqZfXsVYAAEwhwrh1fAMMa7VKbyE8JOdCOUz2aMa9B5FiXEIc/Ll4BGwLrfbsDKLrce/mYy1tIsRolXIWPQ9j4uiDPyh89J79XN7vaVLSXIjg7QxRRj1oKHsC+jTnv1f5n8OncT6xA53YLT8f/sFrEMUl+zlkn7y34yL20NdbQDMwHJ7CCfjyabYvuvfWBMh2/oKV1ERw8XZJbBmN7lYkih4rKMmq0l1bN9ROuVp0cdLGoZVmyzXW/1j+vPKmk+YJA6pCxUAp6pbF2+iepUaYge5XL9Vr9etMTPB61TJm5CDYBDqbNkeOweaKxINcQFwy0ElmoDMStScf0EK63yMSZ/OfEQUSKt+rIHLJYVf6CpePUAxNLmMTzfcip0xASKc/tMlxIn0N/Yi0o9KWWUWB7LY+wev27T2z7JPDk27TWiGrG+H1kKG1sSL1uiheFv9fYuyzDxaRlO44mV/5/+s5pOlG8Tt6UBjx9VugWLi88DyHb6XtEBrRzcguafebxpH0Jij2dBxwSZItCjopFKo84zMBzDAHCxU4NHPHH2vUaRCUS65V/t4Qoj/CQN6eM53uL59ya+8ASVI2kmJ4idfkLKcib9N7zoICGGd6gWUmC4R2jG7/4Pe9Xq2Oco7pZ0sV9aIydSWWZylgR2jMahuMZXQzJg6Bvjt+idLIzzsjnUG5vrNJqDfqRM0ETiWHDA+Kn1MKZe5HsFU/MQqrpXSf3WQt70lpD4uReg6ge2bE
  template:
    metadata:
      creationTimestamp: null
      name: notification-github-secrets
      namespace: flux-system
    type: Opaque
