---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-mailserver-secrets-system
  namespace: flux-system
spec:
  encryptedData:
    DOMAIN: AgCQX397CWMYtk8gRMYppIZiNtZAwcPj7NBGJVriwdhlvDd70OtYqKLt3Vmu8DeyaLY66V4hCHthjOervv7xysszIcSDz12FY8BxLLIYwZzyY1k/krKeSSJu9MDi28TFGJQdrAG9/xfDPuCr73Sp+TIlBpG14/+Ul3TVAFpWoICpxvVuQx3RuuzJ1nOxm6voR/K3q6//8tEYfwo/ugMzevPwseZMGmT8sy53aooUspRFluNfpcK8H8k0lUSoJhuHanBgdzhZl3gsWm0etUlhKjHDKlngs9le7QmChAf+iWjWqRZf4ucQxE1Ikkyl8w2loUqjKdZcQaD/bxhjy9VIws7q90+trrq5yD5bhzBcwfeS+76rErD8izjDz567CJmLiPt89EL8dKhaSZ5hj1ZMB6j9bku5dmpXp1EV+yVECDoDCd9d77oGBVRSz+8Mj3XzJzAL3F4SbWMsyPb2Vn1lGIWZyZVNO3886VAK1ymMrLMycKmZRE/r8PNqzQq3s9pWQjLcBwo+O/FxBcQin6TdN+PD6FlL6Fjjtt5DW704heL/lRja0jYT4zDc8ZwYydTZzyUvAFkKVO4SKYJInNIq5SMS+8i8cXOHH6Jy9pPyWXdU8AmMEuA5yeZDSllx0kibJpwZW9G6mQuTnraaAMqicq2LYhV3s47O2ye5W3vTK9+9EIwoVeDLWE5+uLrNDivbtR4V/SsxVlGU5RdQSCc=
    POSTMASTER_ADDRESS: AgAsZ3RL3J91/euq4d0qF7k0cj+hoZDYdHPn+3PmSqapTmihrNOXtJEASEFOyPlwdUyCza46AK6PW1XLKfsBfw1zc/dQH74gw/BcCGWqO1inghRxIVl+J6Es4jsRc4SYBsn3tesiXTkdgrMJOEwAA5j3ELTqMpvRHHdmAuJK8qvfq+0rW6XV1b285/G+W1y+9i7aEtkEzj/EQUxZSqhi+PzydHZA6cmRArAQK+jB03PDdenB9wUyrIed3R+GR9YeHGvdEYY65WAMpEI9nqRGF0N1ZWCX8soL5jk1R5OdjIzJjGvpgi2hg6OjyZbyFY4JGmV0sONQhKYqSHKXpTeRGFYmllf81MPrfJOWf0P2rrR05YaSY2/9wdVDRK+hXRsK2Sk8t9qEUo7D1CgqIrGa1FefZ99VdG40sLnMyGMZpSiPnKTgUFzjyOPgqHzcihtRy322K0+GGJdajHHzgL3VezIhPoa3UHGSSDTFtgSQd4Mz5d83TojowMOb/iry+wN9TlXy7CSMpZQCazzXKWaDDBJO8TSx3sF9C402qqoIIInxtZZRxQQYTBRsS2hx9NX0qeH4wUbfa5AAvt0W7NE4b7NjSWq3ELyDdzFsLSB2oRr1Ek+fImibMitgGVLAIF0Wq1fUN+2P06logzRpmrtXsoIpPlwdNM46JLOYrXBqPDprgMhALBNZwlG7vOadO5V65ORo10TBWt1ZE/53cJuwVFjqaBI=
  template:
    metadata:
      creationTimestamp: null
      name: docker-mailserver-secrets-system
      namespace: flux-system
