---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-secrets-system
  namespace: flux-system
spec:
  encryptedData:
    TLD: AgBbku0zob6oMRdkZEoLRlh2UJyHlNhoxJUB0uLYjgV62mghX1Dil3md4OXVmVM7a2/JwU3J3I+twLcc79sxZqA59T3EnifFeoWCRvzosLJJRKUoMOoxSmGQpM0slFMDX/KoB1KreQwsSvq8A9DELHCex0StCWwID5ohqRJdj0+vALXoTevjothbxmY+Q67/2mAJ0JxFybqSkqyioy5G5A7ubJisKr9LAz19gDTjswuehemfpIq6un6NMX/2SHIrEkF2br8CZXpSFNV+WUBy3DfVfKRMLutbo+tZM60JoEHeOgRbnk93fcIJpNW/E8OrntCdmjz/8+HH20w8kcaMgZ2/VzYAS7hN4kNpMNsqdvqfJ9UMtfL894vXYpaPkxKlcSNPBzRS0zTQt+Igaiw4o02kJXeycPDqXRi6ykH4hwIPc4kaCVocixfzjZfRQkurHLICvP+X10mnGoYqk5H8Uyff197FOOSCdCCHxMeNYxMWshZMGa5CzoFqSBHjGiwUi8syMvC72JnVJX3Hp7Dc+7Canaa46Iub5pIn2yu3phUL/tyFL9wxWpa2YYp6kX7OO3KGaJi3Z7C+FcSbj1HVNcaGOhZ1FimUhDB2zqkytRmrkbvr5Gc0Bi2tl2jQR73z99u5Y+0BqNppPExTezVlwrgA6LZ3pqUOxlw4bGxtyyIF4WtLE/OjVGz87Xo7WIiVee7ZsxhL4jBX
  template:
    metadata:
      creationTimestamp: null
      name: ingress-secrets-system
      namespace: flux-system
