---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-secrets-system.yaml
  - cert-manager-secrets-system.yaml
  - cloudflare-ddns-secrets-system.yaml
  - docker-mailserver-secrets-system.yaml
  - authentik-secrets-system.yaml

  - vaultwarden-secrets-system.yaml
