---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cluster-secrets
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - flux-system
          - alloy
          - authentik
          - external
          - grafana
          - home-assistant
          - immich
          - longhorn
          - mail
          - media
          - notification
          - outline
          - prometheus-system
          - romm
          - traefik
          - vaultwarden
          - wallabag
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: gcp-secret-manager
    target:
      name: cluster-secrets
    data:
      - secretKey: DOMAIN
        remoteRef:
          key: cluster_DOMAIN
