---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-secrets
  namespace: outline
spec:
  encryptedData:
    client_id: AgAg6AUkPifZqzoKekDfrF0J9aki+8enRK4WYhElnyKXs4HDoy8u6SCjoLL3QH0k9io320bHfp8liUmeILVRpCLRYcjqKASivMpOn3uIxE00EzJBqWWk5qUogtoFEIVCqgp3/yf/BTiirPZBn7Pw7BxNQVoGTBka2bJjWzo0Ygh+/MusHrWviNCorXfgzBkjM8Xr2poSkAXF+BulBydiTUpMVIVxpaYivqQnQxUMTUM9gEOuihsmh39BhxQGHvB9L1oN7K9XDLXstpmK89K5AEr0KEfHyqzFd6qD4UIgsWqrlNe88jpivP9wyvUs09gQOO2lulsUYKUxpBZESFY2zoU4HvLFU9Wq/ulcJ1zAZiVPvjqSPxeisYR4t12+3xW9WW3xH3C2b77/QR2UNyfu1ajaxK4x959NZNl5agzxaej52w1SSy2vWchIg+PmIepF/xVOCJpeqjqMhMcPCc+c0rtDtUJ3DqnfNHWGEY62d5zjuX86sPfU31MCIFDQ1eAao+mHsQvcUPm9eAQeu+9o20olA8ZvkdYVN0EJRJEB4Bt3ds3bIUdRNO7uesL4d9xg5oS/yMgbBF6//lmcO63t7k9ce6pjveWu3timIO2uWru5huvN5j2LHk8PfsVBNkgGwBuyEcJ1PPn5oYv3Og8mYaxJa1TVUxnpXsn2qL0vUSTNpsiBgu+jZARWV61f8Gkq3KIJ0R0fqezmaLs05PxO776QcJemlWR2RZihOTWqbCijDvNLgaTw7Kmq
    client_secret: AgAtaIGd/qwkyeXShYQXDJ8d2pyGtAKenVc8oq/YjFeqZVL5ljrYgXeUrgWZmuWqPy/1HwbDfo6UdoKTVSmnXMSxBsTw+7/pax61ZXEfCLPBkUEC5K+Bz25iOjiC/neXRKaKZHDzS6LwdtcwpVRQreNi/vucOe9GrzD92B3aWMFUGLFkkiEAveMeNxjPiYn7s6IguPxezH5cAtn2DH/tKlXWQb3m8mWgGoecMRGnGKJd2AyvZj1Qtg4M/PV0CTj87klCOPK6B67vdtpLuce6sP3i1e4aagodKFBAjHcGRNQ55n99MkfuM96v5eGqNZwDnQufEPbXR2Ju75dRvQQbuRsrwo4IFz6mRbuIYIMefjWoH2eXbQ12hL57gDSYd9VQCkKvkNc2GGb35kF9FZPemz92lQDFyixo3NHRaLnrbKjYo7Mna5N0bsN6HIxpNZlp8G7Dj++59aiWVvpySYKI4lrOWuNw7GUgRM84qbYWZeUOYbyP1cCKD/RJR+H0dce2lItZuluYlqj+qQh25Fbwyqmm1tNtNuqBLqySsNOOiIbKHOpuVyT4B/mMlT60rpoSA4ao7oWpxEqoH4gRIkVG1XOW5YMQE+SUyCK8lGt+IOo5SbGwKV+N666TeaI108iTUPCG/+6n5JqpNUlVUtcRcqyek0yUGVcVjMvnJuS5btm13E2V5p5+wpR6Omci1SLCqbry0zIzYv5mtpk9BFaNMSliAo89bpMZM7d4mdpr3LkW1YkOe8H8yExnzor7ZnGcJGV+zWRhpA+R78J2q1DFEMg9g9ZAGVZA0L2pWS1vQ75pfOmA757q7u281UMEsj76p68T7PSh5mQKePVJjWCSSKDbWbx7OntkusN0n6y3XCNM5Q==
  template:
    metadata:
      creationTimestamp: null
      name: auth-secrets
      namespace: outline
    type: Opaque
