---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secrets
  namespace: outline
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: auth-secrets
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: outline_OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: outline_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mail-secrets
  namespace: outline
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mail-secrets
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: outline_MAIL_USERNAME
    - secretKey: password
      remoteRef:
        key: outline_MAIL_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: outline
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: pg-secrets
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: outline_PG_USERNAME
    - secretKey: password
      remoteRef:
        key: outline_PG_PASSWORD
