apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: outline-ingress
  namespace: outline
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`outline.${DOMAIN}`)"
      priority: 10
      services:
        - name: outline
          port: 3000

