apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - postgres-cluster.yaml
  - pvc.yaml
  - helm-release.yaml
  - ingressroute.yaml

components:
  - ../../../../components/cnpg-backups

replacements:
  - source:
      kind: Cluster
      name: outline-postgres
      fieldPath: metadata.name
    targets:
      - select:
          kind: ScheduledBackup
          name: cnpg-backup-barman-daily
        fieldPaths:
          - spec.cluster.name
      - select:
          kind: ScheduledBackup
          name: cnpg-backup-volumesnapshot-daily
        fieldPaths:
          - spec.cluster.name
  - source:
      kind: Cluster
      name: outline-postgres
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Cluster
          name: outline-postgres
        fieldPaths:
          - spec.plugins.0.parameters.serverName
        options:
          delimiter: "/"
          index: 0
  - source:
      kind: Cluster
      name: outline-postgres
      fieldPath: metadata.name
    targets:
      - select:
          kind: Cluster
          name: outline-postgres
        fieldPaths:
          - spec.plugins.0.parameters.serverName
        options:
          delimiter: "/"
          index: 1

