---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-secrets
  namespace: outline
spec:
  encryptedData:
    password: AgBGHxfYp3T070+ThgYU5/H1Q8b2pzMEBZFyCGhMyhcHg13nVE6hBrLzOBBS882JasSRD+BkyVVeGA8mdCk/mUN3Ryyb5egH2G1YUYIWznuS0EEPatk7G0rFbRxMxxFeELNdJZzl3qMRuEXLKgtBW71jx9wuwcdhQq9E0GEB9NfCY8spVBxnaQK10R7e2+LAMSewRsXEDvkjre8btmkfXWB1Bu9GcnxwF4906VHu3QPM1aD4ETiUq/F3w8CRdurqQIKn6geUQoFSXQWIVGUgignndapw1q/os47LGH2qLJ0M3a9hUyGEolbN81RsDFaEG93HcHTA4+ET1yHWGGY0VsRquJ+cc86LgG2Q9kB0lDPU/AApJKC1LeLDc+j5m+UY3W6imEYaiBJ/wg4QFpzMdzNYYcwcJsLpqnm4LXfcTcrdUedUt44kjthaHF1CD0IFliSc+tR+yi+9CwD/lFKGfHql1PVMWXeBYHSPq58XP8Kq7EM8PpJ+Pv+7Pn0UlQ26t9cncZJqrJHFjpO6ThXmocDynk3gpwmfbXJKreeePSMKMI0FBgPUIVSoGzLwniIv9D1RXqLzCXETKCYu7AlgttHtwt8go1YGdgdVOn/ghxSAfi6CwqWjhXkTOlIkscDFb/+cZ7MVcQYZv5kBvyYp1uCI/JtPW/iRXboi930QSrRfwf4cFolYMHOThgmuxI4szPjfLaEJ4Af3CNn3P0COFQ==
    username: AgAco4A1HxoR3d6vOY28nvr5SwKbB0WirqhwuufBajjKK5o0QYZlvhCV4a5g7AxhkKsCsCvxLiFPfyuzZRQySiN8qDsM/xCHkFrk18TZHqvUud35VHE7uCurIijnTfBKpovc/nY8nRp7A8KsC4woxF6C2xCGBdoTpKCDwiCjYeFiysKphU1+CsGuh+07gtqWeuL0lHgrwWjhK4jSf2XjvKMkZZH45ZvJL/U/O4RQDFqtninTI4Cy1QURfTYVeQmastSePSES7LjRA2jhV5LHqFC8yOg++XyPMdKCGTKTywbZmdkiX/xt1XZrYh0CFzQodIZh13Wgki7MY9eEyUNwfXsS4ncD71tHXxvUBNlYmwCXAQQIcxzcIiPKBrkbdRZPAefMfYbVPYeLwLAy0JxiVrgmyBTlGlXdbzjVyGXPxdnSSchGTzRBcVzMMRV+WE8tjVEdtVaMWoB8YSJnutAJnyqULMC6wIYPBhXf+sDlSS4MYky88z9le2eUCBsi7orFzrH6k+vWEYgjLsPzI2c/es5lbNcgCpGh98QQ8yi3fPKOFNKFf3Wq2a6TOeSKLlqBUNRz9pSb9fE1EWsLqJh7BoCiWsXxquu0BMqSFaPZXf0+zUkDbMKO+rpG+r7481BAq7zZjrMlkQMNMTUQ5ZIPfd9ozb2EuWgPM52bpZ8DHWy1F+6KJcTMkcw/Alwkbf3JwBGlwjpNaHxjd+tjGc2heGs=
  template:
    metadata:
      creationTimestamp: null
      name: mail-secrets
      namespace: outline
    type: Opaque
