---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-secrets
  namespace: outline
spec:
  encryptedData:
    password: AgCaztmhu9ao9lM2VisPJ/UjuDPSYt3jYOXyNw3E4z86rne+AzO8dq//svL2S7RthK3qTkry7wB4Nb3Iqb6hhTNX8wKaEmFnqeAGHSmdBKduQp7cqP6L42Emf8jHAY+M25ekmUHXgkx2rSP7sae78dR2Iuugk8VGtTsSOtLCr8n5Fd3boEnYMQUy3feEHpe8MRryb41HysT7M3i2hM0xgVxDCT+9hpObngy/0meVS/29aeSysoxR0Xhp8l2Z7ye2ofWp0f8NTJJrLr0MVBazvyvDkiOIOWe3KvNetUo1CicLzGt15GBQmnuUECPNrr2cioP300+8lsAHANZeh6C8VfDO8/iEVbwlel2dYbXs3+CTVigRiPE0TNR+6C3CsMVbWSyOJtWXTyoZUbkFttf3VWHmPvNou9EVL2g0uxQs7b2GJCtdfTHkRdgHIHBY4bdKPORSTadS2cjkHs6EI5EBZdxgiIgeJ75H7fCgEf69nN0TsekcNvlfqD0K25IIVPDfy+YI1Q3M27wp6gMAtclHK9iUKD8F9dtDiQX33mgZSqjt94Ltdv25jtApYCcqKBAOiChfHG4MBjlQRyX9igj+Lt33Q2MGZIWmnMJTIZiXpDTQBr2HyDPFnzWut7NX62DvI1OAuH+7DjmHRcWzZKdkpeJYjuIFJ9Aa2XcmqUU17FjJyMo9O9RBOmHdY5YHtzTdLGcag1cynBZTYoaH6U6bBKsTvE/cs+CEEDJEPVSwhA1Guyew0J9FkmPEU7hCIeUhjubEt7bu
    username: AgAjAn3k+nsbHglumLTxkzADL7fM6jMdlKAVEFhsP2iuOMgN6Sb6wPV5GeYqZK1zFFDf31lG9mauOcseXUQIFIy5a0noAJCmxc3rWocqaliL5RjtLH3Ft/52PxDno6O9IXF67OBLIsFkShyH20R5xj+FVdVS+5Sq+c3Tt/Kp6sOwXEx2asW2dg+zKfSzivDjOIPogiLbk/51HOZqj4z0YmtUJLrgDYTkt3d6ACwLCDLGgMjiHHFlzRphwA/afAGWmeO63oclkozhmK84O9JY6AFoB/DbKMzZJ+1oZa99Uuxf+9GYSXsP69bbH09cFfrIXfJb5pZzsTsQHuFn6o6hlpwKSHXMQ9BJYV0FTTLE8LBIAjBVr4BXrcDcHkwb4VgUNM4WTL6VDerAZa6UZe2MUZmPEDB3Q0Edgv0SxudyHV0NRfvZkYONKdhRwK9F7tpcxt/cwycTyZQB3z0XxuFDlw+Px5lexwia1m4+MqaOnPtMptNvAN66YM4kdV7wTYuA6WPXsYX7MuIF311GpfcRRykJ5pzYCVK06gNuTXNHeOe6sPbOYJUqV1TOeS5+yA2BWgYMTcrOVBMkvAgp9FmMCIEcU25mek6GtB3EsPnH8otiV5gaxZd1KEuyOyAkvSOXVVieHFrgCEy5HrHiQ57hyfsoGliuLgBpD8qC2VQaEStCXU7Bvj05TpbiAdHJLHqEFhQCXmI1xHdM
  template:
    metadata:
      creationTimestamp: null
      name: pg-secrets
      namespace: outline
    type: kubernetes.io/basic-auth
