apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: outline-postgres
  namespace: outline
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5
  primaryUpdateStrategy: unsupervised

  storage:
    size: 2Gi

  managed:
    roles:
      - name: outline
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: outline
      owner: outline
      secret:
        name: pg-secrets
